// ############################################################################
// AI_HEADER: MODULE_GRACE_ESLINT_PLUGIN
// ROLE: Custom ESLint flat-config plugin enforcing W-1.1B contract boundary on
//   the frontend (W-2.0, variant C, lint half).
// DEPENDENCIES: none (pure ESTree visitors, no third-party rule helpers)
// GRACE_ANCHORS: [RULE_CONTRACTS_ONLY_IMPORT, RULE_NO_REDECLARE_CONTRACT_TYPES]
// ############################################################################

// START_MODULE_CONTRACT: M-WEB-LINT.grace-plugin
// purpose: Provide two AST-level rules that the comment-based bash gate cannot
//   express:
//     1. contracts-only-import: payload types may be imported only from
//        "@/packages/contracts" (barrel) or "./_generated" (inside the
//        contracts package itself). Any other path is a violation.
//     2. no-redeclare-contract-types: a TS interface or type alias whose name
//        matches a generated schema name is forbidden in enforced files.
// owns:
//   - eslint-rules/grace-plugin.mjs
// inputs:
//   - source files filtered by eslint.config.mjs (whitelist from
//     grace/frontend.paths).
// outputs:
//   - lint diagnostics with messageIds
// dependencies:
//   - packages/contracts/_generated.ts (read at lint time to discover the set
//     of generated schema names — keeps the rule in lockstep with W-1.1B SoT)
// side_effects:
//   - reads _generated.ts from disk once per ESLint run (cached on plugin load)
// invariants:
//   - MUST NOT mutate AST
//   - MUST NOT depend on any non-stdlib package
//   - the set of "contract names" is derived from the generated file, never
//     hardcoded — Pydantic remains the single SoT
// failure_policy:
//   - if _generated.ts is missing or unparseable, the rule reports a single
//     diagnostic on Program node and disables itself for that run rather than
//     silently passing. This keeps a broken pipeline visible.
// non_goals:
//   - runtime validation, zod inference, codegen
// END_MODULE_CONTRACT: M-WEB-LINT.grace-plugin

// START_MODULE_MAP: M-WEB-LINT.grace-plugin
// public_entrypoints:
//   - default export { rules: { "contracts-only-import",
//                                "no-redeclare-contract-types" } }
// semantic_blocks:
//   - RULE_CONTRACTS_ONLY_IMPORT
//   - RULE_NO_REDECLARE_CONTRACT_TYPES
// owned_tests:
//   - scripts/grace/check-negative.sh (cases NEG-LINT-1, NEG-LINT-2)
// END_MODULE_MAP: M-WEB-LINT.grace-plugin

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const GENERATED_PATH = resolve(__dirname, "..", "packages", "contracts", "_generated.ts");

// Derive contract type names from _generated.ts. We parse a tiny subset by
// regex on purpose: no TS compiler dependency, and the autogenerated file has
// a stable "    Name: {" shape per schema.
let contractNames = null;
let loadError = null;

function loadContractNames() {
  if (contractNames !== null || loadError !== null) return;
  try {
    const src = readFileSync(GENERATED_PATH, "utf8");
    // Match indented "Name: {" lines inside the schemas block. The schema
    // names are PascalCase identifiers; we filter to those.
    const set = new Set();
    const re = /^\s{8}([A-Z][A-Za-z0-9_]+):\s*\{/gm;
    let m;
    while ((m = re.exec(src)) !== null) set.add(m[1]);
    if (set.size === 0) {
      loadError = `no schemas parsed from ${GENERATED_PATH}`;
      return;
    }
    contractNames = set;
  } catch (err) {
    loadError = `cannot read ${GENERATED_PATH}: ${err.message}`;
  }
}

// START_BLOCK: RULE_CONTRACTS_ONLY_IMPORT
const ALLOWED_PAYLOAD_SOURCES = new Set([
  "@/packages/contracts",
  "@/packages/contracts/index",
  "../../packages/contracts",
  "../packages/contracts",
  "./_generated", // only meaningful inside packages/contracts itself
  "./index",
]);

const contractsOnlyImport = {
  meta: {
    type: "problem",
    docs: {
      description:
        "Payload contract types may be imported only from the contracts barrel (@/packages/contracts).",
    },
    messages: {
      foreignImport:
        "GRACE W-1.1B: contract type '{{name}}' must be imported from '@/packages/contracts', got '{{source}}'.",
      pluginBroken:
        "GRACE W-2.0: grace-plugin disabled — {{reason}}. Run pnpm contracts:generate.",
    },
    schema: [],
  },
  create(context) {
    loadContractNames();
    if (loadError) {
      return {
        Program(node) {
          context.report({ node, messageId: "pluginBroken", data: { reason: loadError } });
        },
      };
    }
    const filename = context.filename || context.getFilename();
    // The barrel and the generated file are themselves allowed to reference
    // _generated — they are the boundary, not consumers of it.
    if (filename.includes("/packages/contracts/")) return {};

    return {
      ImportDeclaration(node) {
        if (!node.specifiers || node.specifiers.length === 0) return;
        const source = node.source.value;
        for (const spec of node.specifiers) {
          if (spec.type !== "ImportSpecifier") continue;
          const imported = spec.imported && spec.imported.name;
          if (!imported) continue;
          if (!contractNames.has(imported)) continue;
          if (ALLOWED_PAYLOAD_SOURCES.has(source)) continue;
          context.report({
            node: spec,
            messageId: "foreignImport",
            data: { name: imported, source },
          });
        }
      },
    };
  },
};
// END_BLOCK: RULE_CONTRACTS_ONLY_IMPORT

// START_BLOCK: RULE_NO_REDECLARE_CONTRACT_TYPES
const noRedeclareContractTypes = {
  meta: {
    type: "problem",
    docs: {
      description:
        "Local interface or type alias must not shadow a generated contract schema name.",
    },
    messages: {
      redeclared:
        "GRACE W-1.1B: '{{name}}' is a generated contract type. Do not redeclare it locally — import it from '@/packages/contracts'.",
      pluginBroken:
        "GRACE W-2.0: grace-plugin disabled — {{reason}}. Run pnpm contracts:generate.",
    },
    schema: [],
  },
  create(context) {
    loadContractNames();
    if (loadError) {
      return {
        Program(node) {
          context.report({ node, messageId: "pluginBroken", data: { reason: loadError } });
        },
      };
    }
    const filename = context.filename || context.getFilename();
    if (filename.includes("/packages/contracts/")) return {};

    function check(node, name) {
      if (contractNames.has(name)) {
        context.report({ node, messageId: "redeclared", data: { name } });
      }
    }
    return {
      TSInterfaceDeclaration(node) {
        if (node.id && node.id.name) check(node, node.id.name);
      },
      TSTypeAliasDeclaration(node) {
        if (node.id && node.id.name) check(node, node.id.name);
      },
    };
  },
};
// END_BLOCK: RULE_NO_REDECLARE_CONTRACT_TYPES

export default {
  rules: {
    "contracts-only-import": contractsOnlyImport,
    "no-redeclare-contract-types": noRedeclareContractTypes,
  },
};
