# ############################################################################
# AI_HEADER: SCRIPT_CONTRACTS_EXPORT_OPENAPI
# ROLE: Generate packages/contracts/openapi.json from Pydantic schemas
#       (Option B — Pydantic is the source of truth).
# DEPENDENCIES: fastapi, app.schemas.contract_registry
# GRACE_ANCHORS: [SCHEMA_REGISTRY, OPENAPI_DUMP]
# ############################################################################

# START_MODULE_CONTRACT: SCRIPT_CONTRACTS_EXPORT_OPENAPI
# purpose: Construct a *throw-away* FastAPI application whose only purpose is
#          to expose every public Pydantic schema as a response_model on a
#          dummy endpoint so that FastAPI's openapi generator emits each one
#          as a top-level component schema from the explicit public registry.
#          Then write the resulting OpenAPI document to packages/contracts/openapi.json.
# invariants:
#   - The dummy app is NEVER served. Endpoints exist solely to anchor schemas
#     into the openapi.components.schemas registry.
#   - Output is deterministic: keys are sorted, indent fixed, trailing newline.
#     This is what makes `git diff --exit-code packages/contracts/openapi.json`
#     a reliable drift gate in CI.
#   - Every public root comes from app.schemas.contract_registry as a real class
#     object. String getattr lookup is forbidden to keep generation explicit.
# emits: packages/contracts/openapi.json (overwritten in place).
# consumes: app.schemas.contract_registry (the explicit public root registry).
# END_MODULE_CONTRACT

# START_MODULE_MAP: SCRIPT_CONTRACTS_EXPORT_OPENAPI
# - main(): entrypoint. Resolves repo root, builds dummy app, writes file.
# - _build_app(): constructs the FastAPI() and registers one GET route per
#                 validated public registry root.
# END_MODULE_MAP

# START_BLOCK: IMPORTS
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

# Ensure `app` package is importable when this script is run from repo root.
HERE = Path(__file__).resolve()
REPO_ROOT = HERE.parents[2]
API_ROOT = REPO_ROOT / "apps" / "api"
sys.path.insert(0, str(API_ROOT))

from fastapi import FastAPI  # noqa: E402

from app.schemas.contract_registry import (  # noqa: E402
    PUBLIC_CONTRACT_ROOTS,
    validate_public_contract_roots,
)
# END_BLOCK: IMPORTS


# START_BLOCK: APP_BUILDER
def _build_app() -> FastAPI:
    """Construct the throw-away FastAPI app used solely to dump openapi.json.

    Each model becomes a no-op GET endpoint with `response_model=Model`. We
    don't care about the path — only that FastAPI emits each schema into
    `components.schemas`.
    """

    app = FastAPI(
        title="Astro API — contract surface",
        version="0.0.0-contracts",
        description=(
            "Generated by scripts/contracts/export_openapi.py. Do not edit by "
            "hand. This document is the single source of truth for "
            "packages/contracts/*.ts (Option B per W-1.1B)."
        ),
    )

    for model in validate_public_contract_roots(PUBLIC_CONTRACT_ROOTS):
        slug = model.__name__.lower()

        # We can't use a default-arg closure here because FastAPI inspects
        # endpoint signatures and would surface the class as a parameter
        # default, triggering Pydantic JSON-schema warnings. A factory
        # function gives us a fresh, parameter-less stub per model.
        def _make_stub() -> Any:
            def _stub() -> Any:  # pragma: no cover
                raise NotImplementedError("dummy endpoint, never served")

            return _stub

        app.add_api_route(
            path=f"/__contracts__/{slug}",
            endpoint=_make_stub(),
            methods=["GET"],
            response_model=model,
            name=f"contracts__{slug}",
            include_in_schema=True,
            tags=["__contracts__"],
        )

    return app
# END_BLOCK: APP_BUILDER


# START_BLOCK: MAIN
def main() -> int:
    out_path = REPO_ROOT / "packages" / "contracts" / "openapi.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    app = _build_app()
    doc = app.openapi()

    # Stamp our generator metadata so reviewers immediately know this file
    # is generated and how to regenerate it.
    doc.setdefault("info", {})
    doc["info"]["x-generator"] = "scripts/contracts/export_openapi.py"
    doc["info"]["x-source-of-truth"] = "apps/api/app/schemas/* (Pydantic v2)"

    payload = json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False)
    out_path.write_text(payload + "\n", encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)} ({len(payload)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
# END_BLOCK: MAIN
