#!/usr/bin/env bash

# ############################################################################
# AI_HEADER: MODULE_CONTRACTS_GENERATE
# ROLE: Tooling script
# DEPENDENCIES: local modules
# GRACE_ANCHORS: []
# SLICE: SLICE-GUARDRAILS-TOOLING
# #########################################// START_MODULE_CONTRACT
# purpose: Tool: generate
# owns:
#   - scripts/contracts/generate.sh
# inputs: Function args
# outputs: Return values
# dependencies: local modules
# side_effects: n/a (pure)
# emitted_logs: n/a (pure)
# invariants:
#   - n/a
# failure_policy: log and raise
# END_MODULE_CONTRACT
# ############################################################################
# scripts/contracts/generate.sh
# ROLE: One-shot regeneration pipeline for Option B (W-1.1B).
#       Pydantic schemas → openapi.json → _generated.ts → per-feature shims.
# Invariant: this script is idempotent. Running it twice in a row produces a
#            byte-identical tree; CI uses `git diff --exit-code` after running
#            it as the drift gate.
# ############################################################################
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

# Resolve a Python interpreter that has the API deps installed. Local devs
# typically activate apps/api/.venv; CI installs deps into the system Python
# of the job. We prefer the venv if present so `make contracts` works without
# any prior `source` step.
if [[ -x "apps/api/.venv/bin/python" ]]; then
  PYTHON="apps/api/.venv/bin/python"
else
  PYTHON="${PYTHON:-python3}"
fi

# 1. Pydantic → openapi.json  --------------------------------------------------
"$PYTHON" scripts/contracts/export_openapi.py

# 2. openapi.json → _generated.ts ---------------------------------------------
# `--alphabetize` keeps the output deterministic across openapi-typescript
# minor versions. `--root-types` would inline schemas at the top level but
# we deliberately keep the `components["schemas"]` namespace so per-feature
# shims can re-export by name.
npx --yes openapi-typescript packages/contracts/openapi.json \
  --output packages/contracts/_generated.ts \
  --alphabetize \
  >/dev/null

# 3. Stamp generation banner so the file fails human review if hand-edited.
{
  echo "/* eslint-disable */"
  echo "// AUTOGENERATED by scripts/contracts/generate.sh — DO NOT EDIT."
  echo "// Source of truth: apps/api/app/schemas/* (Pydantic, Option B / W-1.1B)."
  echo "// Regenerate with: pnpm contracts:generate"
  cat packages/contracts/_generated.ts
} > packages/contracts/_generated.ts.tmp
mv packages/contracts/_generated.ts.tmp packages/contracts/_generated.ts

echo "contracts: regenerated openapi.json + _generated.ts"
