/* eslint-disable */
// AUTOGENERATED by scripts/contracts/generate.sh — DO NOT EDIT.
// Source of truth: apps/api/app/schemas/* (Pydantic, Option B / W-1.1B).
// Regenerate with: pnpm contracts:generate
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/__contracts__/accesssummary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Accesssummary */
        get: operations["contracts__accesssummary___contracts___accesssummary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/autherror": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Autherror */
        get: operations["contracts__autherror___contracts___autherror_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/authsession": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Authsession */
        get: operations["contracts__authsession___contracts___authsession_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/birthdata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Birthdata */
        get: operations["contracts__birthdata___contracts___birthdata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/calendarpayload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Calendarpayload */
        get: operations["contracts__calendarpayload___contracts___calendarpayload_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/horaryanswerread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Horaryanswerread */
        get: operations["contracts__horaryanswerread___contracts___horaryanswerread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/horaryquestioncreate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Horaryquestioncreate */
        get: operations["contracts__horaryquestioncreate___contracts___horaryquestioncreate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/horaryquestionread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Horaryquestionread */
        get: operations["contracts__horaryquestionread___contracts___horaryquestionread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/horaryquotaread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Horaryquotaread */
        get: operations["contracts__horaryquotaread___contracts___horaryquotaread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/locationdata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Locationdata */
        get: operations["contracts__locationdata___contracts___locationdata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/natalpayload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Natalpayload */
        get: operations["contracts__natalpayload___contracts___natalpayload_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/profileread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Profileread */
        get: operations["contracts__profileread___contracts___profileread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/profilewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Profilewrite */
        get: operations["contracts__profilewrite___contracts___profilewrite_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/telegramauthrequest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Telegramauthrequest */
        get: operations["contracts__telegramauthrequest___contracts___telegramauthrequest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__contracts__/todaypayload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contracts  Todaypayload */
        get: operations["contracts__todaypayload___contracts___todaypayload_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessSummary */
        AccessSummary: {
            /** Accessuntil */
            accessUntil?: string | null;
            /** Referraldaysleft */
            referralDaysLeft: number;
            /** Subscriptionactive */
            subscriptionActive: boolean;
            /**
             * User
             * @enum {string}
             */
            user: "trial" | "subscription" | "expired" | "none";
        };
        /**
         * ActivationEvidence
         * @description Convergence: несколько техник указывают на одну планету/дом/сферу
         */
        ActivationEvidence: {
            /**
             * Convergencelevel
             * @enum {string}
             */
            convergenceLevel: "double" | "triple" | "quad" | "peak";
            /** Summary */
            summary: string;
            /** Techniques */
            techniques: string[];
            /** Theme */
            theme: string;
        };
        /** AllowedRange */
        AllowedRange: {
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /** ParagraphBlock */
        app__schemas__horary__ParagraphBlock: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "paragraph";
        };
        /** QuoteBlock */
        app__schemas__horary__QuoteBlock: {
            /** Source */
            source?: string | null;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "quote";
        };
        /** ParagraphBlock */
        app__schemas__natal__ParagraphBlock: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "paragraph";
        };
        /** QuoteBlock */
        app__schemas__natal__QuoteBlock: {
            /** Source */
            source?: string | null;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "quote";
        };
        /**
         * AuthError
         * @description Stable error envelope for 400 and 401 bodies on /api/auth/*.
         */
        AuthError: {
            /**
             * Code
             * @enum {string}
             */
            code: "INVALID_HMAC" | "MISSING_FIELDS" | "MALFORMED_INITDATA" | "INITDATA_EXPIRED" | "UNAUTHORIZED";
            /** Message */
            message: string;
        };
        /**
         * AuthSession
         * @description POST /api/auth/telegram — 200 response body.
         *
         *     The opaque session token itself is NEVER in the body; it travels in the
         *     HttpOnly Set-Cookie header.
         */
        AuthSession: {
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Isnewuser */
            isNewUser: boolean;
            /**
             * Userid
             * Format: uuid
             */
            userId: string;
        };
        /**
         * BirthData
         * @description Birth-place + birth-time data. Every field is optional (incremental
         *     onboarding). Validators enforce per-field ranges and lat/lon co-presence.
         */
        BirthData: {
            /** Birthcity */
            birthCity?: string | null;
            /** Birthday */
            birthday?: string | null;
            /** Birthlat */
            birthLat?: number | null;
            /** Birthlon */
            birthLon?: number | null;
            /** Birthtime */
            birthTime?: string | null;
            /** Birthtz */
            birthTz?: string | null;
        };
        /** BulletsBlock */
        BulletsBlock: {
            /** Items */
            items: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bullets";
        };
        /** CalendarDay */
        CalendarDay: {
            access?: components["schemas"]["ContentAccessState"] | null;
            /** Date */
            date: string;
            /** Daynumber */
            dayNumber: number;
            /** Daystatus */
            dayStatus?: ("supportive" | "steady" | "tense") | null;
            /** Disabled */
            disabled: boolean;
            /** Iscurrentmonth */
            isCurrentMonth: boolean;
            /** Istoday */
            isToday: boolean;
        };
        /** CalendarMeta */
        CalendarMeta: {
            /** Contractversion */
            contractVersion: number;
            /** Generatedat */
            generatedAt: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "calendar/v1";
        };
        /** CalendarPayload */
        CalendarPayload: {
            allowedRange: components["schemas"]["AllowedRange"];
            /** Days */
            days: components["schemas"]["CalendarDay"][];
            meta: components["schemas"]["CalendarMeta"];
            /** Month */
            month: string;
            /** Title */
            title: string;
        };
        /** CalloutBlock */
        CalloutBlock: {
            /** Text */
            text: string;
            /** Title */
            title?: string | null;
            /** Tone */
            tone?: ("neutral" | "strength" | "risk" | "insight") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "callout";
        };
        /** ContentAccessState */
        ContentAccessState: {
            /** Accessuntil */
            accessUntil?: string | null;
            /** Reason */
            reason?: ("active_referral_days" | "active_subscription" | "expired_access" | "outside_access_window") | null;
            /** Referraldaysleft */
            referralDaysLeft?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "full" | "preview" | "locked";
            /** Subscriptionactive */
            subscriptionActive?: boolean | null;
        };
        /** DayQuality */
        DayQuality: {
            /** Frictionscore */
            frictionScore: number;
            /** Intensityscore */
            intensityScore: number;
            /** Supportscore */
            supportScore: number;
        };
        /** DividerBlock */
        DividerBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "divider";
        };
        /** HeadingBlock */
        HeadingBlock: {
            /**
             * Level
             * @enum {integer}
             */
            level: 2 | 3;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "heading";
        };
        /** HighlightItem */
        HighlightItem: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Title */
            title: string;
            /** Tone */
            tone?: string | null;
        };
        /** HighlightsBlock */
        HighlightsBlock: {
            /** Items */
            items: components["schemas"]["HighlightItem"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "highlights";
        };
        /** HoraryAnswerRead */
        HoraryAnswerRead: {
            /** Blocks */
            blocks: (components["schemas"]["app__schemas__horary__ParagraphBlock"] | components["schemas"]["LeadBlock"] | components["schemas"]["HeadingBlock"] | components["schemas"]["ListBlock"] | components["schemas"]["CalloutBlock"] | components["schemas"]["ProsConsBlock"] | components["schemas"]["DividerBlock"] | components["schemas"]["app__schemas__horary__QuoteBlock"] | components["schemas"]["VerdictCardBlock"] | components["schemas"]["TestimoniesBlock"] | components["schemas"]["TimingBlock"])[];
            /** Confidence */
            confidence: number;
            /**
             * Confidenceexplanation
             * @default
             */
            confidenceExplanation: string;
            /**
             * Confidencelabel
             * @default medium
             * @enum {string}
             */
            confidenceLabel: "low" | "medium" | "high";
            /** Generatedat */
            generatedAt: string;
            /** Planets */
            planets: string[];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "yes" | "no" | "maybe";
        };
        /** HoraryQuestionCreate */
        HoraryQuestionCreate: {
            /** Category */
            category?: ("love" | "career" | "money" | "health" | "travel" | "other") | null;
            /** Clientlocaltime */
            clientLocalTime?: string | null;
            /** Clienttimezone */
            clientTimezone: string;
            /** Idempotencykey */
            idempotencyKey: string;
            /** Questionlat */
            questionLat?: number | null;
            /** Questionlocationname */
            questionLocationName?: string | null;
            /** Questionlon */
            questionLon?: number | null;
            /** Text */
            text: string;
        };
        /** HoraryQuestionRead */
        HoraryQuestionRead: {
            answer?: components["schemas"]["HoraryAnswerRead"] | null;
            /** Category */
            category: string | null;
            /** Clientlocaltime */
            clientLocalTime: string | null;
            /** Clienttimezone */
            clientTimezone: string;
            /** Createdat */
            createdAt: string;
            /**
             * Creditrefunded
             * @default false
             */
            creditRefunded: boolean;
            /** Failurestage */
            failureStage?: string | null;
            /** Id */
            id: string;
            /** Publicerrorcode */
            publicErrorCode?: string | null;
            /** Publicerrormessage */
            publicErrorMessage?: string | null;
            /** Questionlocationname */
            questionLocationName?: string | null;
            /** Spentcreditsource */
            spentCreditSource?: ("subscription_weekly_free" | "referral_bonus" | "gift" | "paid" | "adjustment") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "answered" | "failed" | "refunded" | "expired";
            /** Text */
            text: string;
        };
        /** HoraryQuotaRead */
        HoraryQuotaRead: {
            /** Bonuscredits */
            bonusCredits: number;
            /**
             * Canpurchase
             * @default true
             */
            canPurchase: boolean;
            /** Nextweeklyfreeat */
            nextWeeklyFreeAt?: string | null;
            /** Paidcredits */
            paidCredits: number;
            /** Weeklyfreeavailable */
            weeklyFreeAvailable: boolean;
            /** Weeklyfreeexpiresat */
            weeklyFreeExpiresAt?: string | null;
        };
        /** LeadBlock */
        LeadBlock: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "lead";
        };
        /** ListBlock */
        ListBlock: {
            /** Items */
            items: string[];
            /** Style */
            style?: ("bullet" | "check") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "list";
        };
        /** LocationData */
        LocationData: {
            /** City */
            city?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Tz */
            tz?: string | null;
        };
        /**
         * ManifestationZone
         * @description Где это проявится в жизни
         */
        ManifestationZone: {
            /** Description */
            description: string;
            /** House */
            house: number;
            /**
             * Intensity
             * @enum {string}
             */
            intensity: "background" | "active" | "peak";
            /** Theme */
            theme: string;
        };
        /** MicrocopyItem */
        MicrocopyItem: {
            /** Id */
            id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "today" | "morning" | "evening";
            /** Textlong */
            textLong: string;
            /** Textshort */
            textShort: string;
            /** Tone */
            tone: ("bold" | "supportive" | "gentle" | "warning")[];
        };
        /** NatalMeta */
        NatalMeta: {
            /** Calculationversion */
            calculationVersion?: number | null;
            /** Contractversion */
            contractVersion: number;
            /** Generatedat */
            generatedAt: string;
            /** Interpretationversion */
            interpretationVersion?: number | null;
            person?: components["schemas"]["Person"] | null;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "natal/v1";
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
        };
        /** NatalPayload */
        NatalPayload: {
            meta: components["schemas"]["NatalMeta"];
            /** Sections */
            sections: components["schemas"]["NatalSection"][];
        };
        /** NatalSection */
        NatalSection: {
            /** Blocks */
            blocks: (components["schemas"]["app__schemas__natal__ParagraphBlock"] | components["schemas"]["BulletsBlock"] | components["schemas"]["HighlightsBlock"] | components["schemas"]["app__schemas__natal__QuoteBlock"])[];
            /** Iconname */
            iconName?: string | null;
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /**
         * PeriodContext
         * @description Почему это важно именно сейчас (фон периода)
         */
        PeriodContext: {
            /** Activeperiod */
            activePeriod?: string | null;
            /** Longtermtransit */
            longTermTransit?: string | null;
            /** Solarreturnemphasis */
            solarReturnEmphasis?: string | null;
            /** Yearruler */
            yearRuler?: string | null;
            /** Yeartheme */
            yearTheme?: string | null;
        };
        /** Person */
        Person: {
            birth?: components["schemas"]["PersonBirth"] | null;
            /** Name */
            name?: string | null;
        };
        /** PersonBirth */
        PersonBirth: {
            /** Date */
            date: string;
            /** Place */
            place?: string | null;
            /** Time */
            time?: string | null;
        };
        /**
         * ProfileRead
         * @description Response shape for GET /api/profile. Privacy: NO tg_user_id, NO tokens.
         */
        ProfileRead: {
            birth: components["schemas"]["BirthData"];
            birthdayLocation?: components["schemas"]["LocationData"] | null;
            currentLocation?: components["schemas"]["LocationData"] | null;
            /** Firstname */
            firstName?: string | null;
            /** Gender */
            gender?: string | null;
            /** Isonboarded */
            isOnboarded?: boolean;
            /**
             * Userid
             * Format: uuid
             */
            userId: string;
        };
        /**
         * ProfileWrite
         * @description Request body for PUT /api/profile.
         *
         *     Field-level partial: omitted top-level fields are 'unchanged'. The
         *     `birth` block is itself a BirthData (also optional fields), so callers
         *     can update e.g. only `birthCity` by sending `{"birth": {"birthCity": "..."}}`.
         */
        ProfileWrite: {
            birth?: components["schemas"]["BirthData"];
            birthdayLocation?: components["schemas"]["LocationData"] | null;
            currentLocation?: components["schemas"]["LocationData"] | null;
            /** Firstname */
            firstName?: string | null;
            /** Gender */
            gender?: "male" | "female" | null;
        };
        /** ProsConsBlock */
        ProsConsBlock: {
            /** Cons */
            cons?: string[] | null;
            /** Conslabel */
            consLabel?: string | null;
            /** Pros */
            pros?: string[] | null;
            /** Proslabel */
            prosLabel?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pros_cons";
        };
        /** ReadingBody */
        ReadingBody: {
            /** Paragraphs */
            paragraphs: string[];
        };
        /**
         * TelegramAuthRequest
         * @description POST /api/auth/telegram — request body.
         */
        TelegramAuthRequest: {
            /** Initdata */
            initData: string;
        };
        /**
         * TestimoniesBlock
         * @description Свидетельства «за», «против» и нейтральные факторы.
         */
        TestimoniesBlock: {
            /** Cons */
            cons?: components["schemas"]["TestimonyItem"][];
            /**
             * Conslabel
             * @default Свидетельства «против»
             */
            consLabel: string;
            /** Neutral */
            neutral?: components["schemas"]["TestimonyItem"][];
            /**
             * Neutrallabel
             * @default Нейтральные факторы
             */
            neutralLabel: string;
            /** Pros */
            pros?: components["schemas"]["TestimonyItem"][];
            /**
             * Proslabel
             * @default Свидетельства «за»
             */
            prosLabel: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "testimonies";
        };
        /** TestimonyItem */
        TestimonyItem: {
            /** Aspecttype */
            aspectType?: string | null;
            /** Explanation */
            explanation: string;
            /** Orb */
            orb?: number | null;
            /** Planets */
            planets?: string[];
            /** Title */
            title: string;
            /** Weight */
            weight: number;
        };
        /**
         * TimingBlock
         * @description Блок со сроками реализации.
         *
         *     status="known"            — есть выраженный срок, time_range обязателен.
         *     status="unclear"          — карта не даёт точного срока, time_range
         *                                 опционален (типовая оценка по категории).
         *     status="not_enough_evidence" — срок не выражен и не выводится, time_range=None.
         */
        TimingBlock: {
            /**
             * Status
             * @enum {string}
             */
            status: "known" | "unclear" | "not_enough_evidence";
            /** Text */
            text: string;
            /** Timerange */
            timeRange?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "timing";
        };
        /** TodayAction */
        TodayAction: {
            /** Href */
            href?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * TodayImportantEvent
         * @description Today Important block event.
         */
        TodayImportantEvent: {
            /** Endsat */
            endsAt?: string | null;
            /** Exactat */
            exactAt?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "void_moon" | "new_moon" | "full_moon" | "solar_eclipse" | "lunar_eclipse" | "mercury_retrograde" | "mercury_station" | "moon_quarter" | "sun_ingress" | "fast_planet_aspect";
            /** Localtimelabel */
            localTimeLabel?: string | null;
            /**
             * Priority
             * @default 5
             */
            priority: number;
            /** Startsat */
            startsAt?: string | null;
            /** Summary */
            summary: string;
            /** Timezone */
            timezone: string;
            /** Title */
            title: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "supportive" | "caution" | "neutral_shift";
        };
        /** TodayMeta */
        TodayMeta: {
            /** Activationlayerversion */
            activationLayerVersion?: number | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Calculationversion */
            calculationVersion: number;
            /** Contentversion */
            contentVersion: number;
            /** Contractversion */
            contractVersion: number;
            /** Generatedat */
            generatedAt: string;
            /** Normalizationversion */
            normalizationVersion: number;
            /** Promptversion */
            promptVersion: number;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "today/v1";
            /** Scoringcanonversion */
            scoringCanonVersion?: number | null;
            /** Scoringversion */
            scoringVersion: number;
        };
        /** TodayPayload */
        TodayPayload: {
            access: components["schemas"]["ContentAccessState"];
            /** Actions */
            actions?: components["schemas"]["TodayAction"][] | null;
            /** Activationevidence */
            activationEvidence?: components["schemas"]["ActivationEvidence"][] | null;
            /** Date */
            date: string;
            dayQuality?: components["schemas"]["DayQuality"] | null;
            /**
             * Daystatus
             * @enum {string}
             */
            dayStatus: "supportive" | "steady" | "tense";
            /** Headline */
            headline: string;
            /**
             * Importanttoday
             * @default []
             */
            importantToday: components["schemas"]["TodayImportantEvent"][];
            /** Manifestationzones */
            manifestationZones?: components["schemas"]["ManifestationZone"][] | null;
            meta: components["schemas"]["TodayMeta"];
            /** Microcopy */
            microcopy: components["schemas"]["MicrocopyItem"][];
            /** Notes */
            notes?: string | null;
            periodContext?: components["schemas"]["PeriodContext"] | null;
            reading: components["schemas"]["ReadingBody"];
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
            /** Topflags */
            topFlags: components["schemas"]["TopFlag"][];
            /** Weekstrip */
            weekStrip: components["schemas"]["WeekStripDay"][];
            whyThisHappens: components["schemas"]["WhyThisHappens"];
            yesterdayEcho?: components["schemas"]["YesterdayEcho"] | null;
        };
        /** TopFlag */
        TopFlag: {
            hint?: components["schemas"]["TopFlagHint"] | null;
            /** Iconname */
            iconName: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** TopFlagHint */
        TopFlagHint: {
            /** Howitfeels */
            howItFeels?: string | null;
            /** Whytoday */
            whyToday?: string | null;
        };
        /**
         * VerdictCardBlock
         * @description Крупная карточка вердикта: да/нет/возможно + label уверенности.
         *
         *     Per W-HORARY-ANSWER-QUALITY-V1 §3.1–3.2 confidence here is shown as
         *     a human label (low/medium/high), NOT as a probability percentage.
         */
        VerdictCardBlock: {
            /** Confidence */
            confidence: number;
            /** Confidenceexplanation */
            confidenceExplanation: string;
            /**
             * Confidencelabel
             * @enum {string}
             */
            confidenceLabel: "low" | "medium" | "high";
            /** Label */
            label?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "verdict_card";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "yes" | "no" | "maybe";
        };
        /** WeekStripDay */
        WeekStripDay: {
            /** Date */
            date: string;
            /**
             * Daystatus
             * @enum {string}
             */
            dayStatus: "supportive" | "steady" | "tense";
            /** Istoday */
            isToday: boolean;
        };
        /** WhyBullets */
        WhyBullets: {
            /** Items */
            items: string[];
            /**
             * Kind
             * @constant
             */
            kind: "bullets";
        };
        /** WhyParagraph */
        WhyParagraph: {
            /**
             * Kind
             * @constant
             */
            kind: "paragraph";
            /** Text */
            text: string;
        };
        /** WhySection */
        WhySection: {
            /** Aspects */
            aspects?: string[] | null;
            /** Blocks */
            blocks: (components["schemas"]["WhyParagraph"] | components["schemas"]["WhyBullets"])[];
            /** Houses */
            houses?: number[] | null;
            /** Iconname */
            iconName?: string | null;
            /** Id */
            id: string;
            /** Layer */
            layer?: ("main_theme" | "daily_layer" | "personal_activation" | "period_background" | "amplifiers" | "softeners" | "manifestation_zones" | "astrological_meaning" | "practical_meaning") | null;
            /** Planets */
            planets?: string[] | null;
            /** Techniques */
            techniques?: string[] | null;
            /** Title */
            title: string;
        };
        /** WhyThisHappens */
        WhyThisHappens: {
            /** Sections */
            sections: components["schemas"]["WhySection"][];
        };
        /** YesterdayEcho */
        YesterdayEcho: {
            /** Accuracy */
            accuracy?: (1 | 2 | 3 | 4 | 5) | null;
            /** Closuretext */
            closureText: string;
            /** Hadcheckin */
            hadCheckin: boolean;
            /** Mood */
            mood?: (1 | 2 | 3 | 4 | 5) | null;
            /**
             * Transition
             * @enum {string}
             */
            transition: "released" | "intensified" | "shifted" | "continued";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    contracts__accesssummary___contracts___accesssummary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSummary"];
                };
            };
        };
    };
    contracts__autherror___contracts___autherror_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    contracts__authsession___contracts___authsession_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
        };
    };
    contracts__birthdata___contracts___birthdata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BirthData"];
                };
            };
        };
    };
    contracts__calendarpayload___contracts___calendarpayload_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarPayload"];
                };
            };
        };
    };
    contracts__horaryanswerread___contracts___horaryanswerread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoraryAnswerRead"];
                };
            };
        };
    };
    contracts__horaryquestioncreate___contracts___horaryquestioncreate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoraryQuestionCreate"];
                };
            };
        };
    };
    contracts__horaryquestionread___contracts___horaryquestionread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoraryQuestionRead"];
                };
            };
        };
    };
    contracts__horaryquotaread___contracts___horaryquotaread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoraryQuotaRead"];
                };
            };
        };
    };
    contracts__locationdata___contracts___locationdata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationData"];
                };
            };
        };
    };
    contracts__natalpayload___contracts___natalpayload_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NatalPayload"];
                };
            };
        };
    };
    contracts__profileread___contracts___profileread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
        };
    };
    contracts__profilewrite___contracts___profilewrite_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWrite"];
                };
            };
        };
    };
    contracts__telegramauthrequest___contracts___telegramauthrequest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramAuthRequest"];
                };
            };
        };
    };
    contracts__todaypayload___contracts___todaypayload_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayPayload"];
                };
            };
        };
    };
}
