// AUTOGENERATED by scripts/contracts/generate.sh — DO NOT EDIT.
// Source of truth: apps/api/app/schemas/* (Pydantic, Option B / W-1.1B).
// Regenerate with: pnpm contracts:generate
// ############################################################################
// AI_HEADER: TEMPLATE_ZOD_SCHEMAS — handlebars template for schemas-only zod generation.
// ROLE: Generates clean schemas-only zod structures from openapi.json.
// ############################################################################

// START_MODULE_CONTRACT: M-TEMPLATE-ZOD-SCHEMAS
// purpose: Template file used by openapi-zod-client to generate _generated.zod.ts.
// owns:
//   - scripts/contracts/templates/zod-schemas.hbs
// inputs: handlebars context from openapi-zod-client
// outputs: TypeScript file text
// dependencies: openapi-zod-client template engine
// side_effects: none
// emitted_logs: none
// invariants:
//   - output imports runtime only from zod
//   - output exports every schemas context entry plus stable `schemas` map
// failure_policy:
//   - template/render failure aborts generator and final artifact is not replaced
// END_MODULE_CONTRACT: M-TEMPLATE-ZOD-SCHEMAS

// START_MODULE_MAP: M-TEMPLATE-ZOD-SCHEMAS
// public_entrypoints:
//   - generated schema declarations
//   - schemas map export
// semantic_blocks:
//   - SCHEMA_DECLARATIONS: exports all generated zod schemas
//   - SCHEMA_MAP: exports unified schema index
// owned_tests:
//   - __tests__/contracts/generated-runtime.test.ts
// END_MODULE_MAP: M-TEMPLATE-ZOD-SCHEMAS

import { z } from "zod";

// START_BLOCK: SCHEMA_DECLARATIONS
export const AccessSummary = z.object({
  accessStart: z.union([z.string(), z.null()]).optional(),
  accessUntil: z.union([z.string(), z.null()]).optional(),
  referralDaysLeft: z.number().int(),
  subscriptionActive: z.boolean(),
  user: z.enum(["trial", "subscription", "expired", "none"]),
});
export const ActivationEvidence = z.object({
  active: z.boolean().optional().default(true),
  activeFrom: z.union([z.string(), z.null()]).optional(),
  activeUntil: z.union([z.string(), z.null()]).optional(),
  angle: z.union([z.string(), z.null()]).optional(),
  applying: z.union([z.boolean(), z.null()]).optional(),
  aspect: z.union([z.string(), z.null()]).optional(),
  debug: z.object({}).partial().passthrough().optional(),
  evidence: z.string(),
  exactAt: z.union([z.string(), z.null()]).optional(),
  house: z.union([z.number(), z.null()]).optional(),
  id: z.string(),
  kind: z.string(),
  lot: z.union([z.string(), z.null()]).optional(),
  orb: z.union([z.number(), z.null()]).optional(),
  phase: z
    .enum(["applying", "exact", "separating", "background", "period"])
    .optional()
    .default("background"),
  polarity: z
    .enum(["supportive", "tense", "mixed", "neutral"])
    .optional()
    .default("neutral"),
  sourceFrame: z.union([z.string(), z.null()]).optional(),
  sourcePlanet: z.union([z.string(), z.null()]).optional(),
  strength: z.number().gte(0).lte(1),
  targetFrame: z.union([z.string(), z.null()]).optional(),
  targetKey: z.string(),
  targetPlanet: z.union([z.string(), z.null()]).optional(),
  targetType: z.enum(["planet", "house", "lot", "angle", "sphere"]),
  technique: z.string(),
  techniqueFamily: z.string(),
  weightHint: z.union([z.number(), z.null()]).optional(),
});
export const ActivationLayer = z.object({
  activationLayerVersion: z.string().optional().default("al-1.1"),
  activations: z.array(ActivationEvidence),
  byAngle: z.record(z.array(z.string())),
  byHouse: z.record(z.array(z.string())),
  byLot: z.record(z.array(z.string())),
  byPlanet: z.record(z.array(z.string())),
  calculationVersion: z.string(),
  houseSystem: z.string(),
  schemaVersion: z.string().optional().default("activation-layer.v1"),
  targetDate: z.string(),
  targetTime: z.string(),
  targetTz: z.string(),
  warnings: z.array(z.string()).optional(),
});
export const AuthError = z.object({
  code: z.enum([
    "INVALID_HMAC",
    "MISSING_FIELDS",
    "MALFORMED_INITDATA",
    "INITDATA_EXPIRED",
    "UNAUTHORIZED",
  ]),
  message: z.string(),
});
export const AuthSession = z.object({
  expiresAt: z.string().datetime({ offset: true }),
  isNewUser: z.boolean(),
  userId: z.string().uuid(),
});
export const BirthData = z
  .object({
    birthCity: z.union([z.string(), z.null()]),
    birthLat: z.union([z.number(), z.null()]),
    birthLon: z.union([z.number(), z.null()]),
    birthTime: z.union([z.string(), z.null()]),
    birthTz: z.union([z.string(), z.null()]),
    birthday: z.union([z.string(), z.null()]),
  })
  .partial();
export const AllowedRange = z.object({ from: z.string(), to: z.string() });
export const ContentAccessState = z.object({
  accessUntil: z.union([z.string(), z.null()]).optional(),
  reason: z
    .union([
      z.enum([
        "active_referral_days",
        "active_subscription",
        "expired_access",
        "outside_access_window",
      ]),
      z.null(),
    ])
    .optional(),
  referralDaysLeft: z.union([z.number(), z.null()]).optional(),
  state: z.enum(["full", "preview", "locked"]),
  subscriptionActive: z.union([z.boolean(), z.null()]).optional(),
});
export const CalendarLunarFields = z
  .object({
    illumination: z.union([z.number(), z.null()]),
    lunarDay: z.union([z.number(), z.null()]),
    moonSign: z.union([z.string(), z.null()]),
    moonSignLabel: z.union([z.string(), z.null()]),
    phase: z.union([
      z.enum([
        "new_moon",
        "waxing_crescent",
        "first_quarter",
        "waxing_gibbous",
        "full_moon",
        "waning_gibbous",
        "last_quarter",
        "waning_crescent",
      ]),
      z.null(),
    ]),
    phaseIndex: z.union([z.number(), z.null()]),
    phaseLabel: z.union([z.string(), z.null()]),
    voidOfCourse: z.union([z.boolean(), z.null()]),
  })
  .partial();
export const CalendarDay = z.object({
  access: z.union([ContentAccessState, z.null()]).optional(),
  date: z.string(),
  dayNumber: z.number().int(),
  dayStatus: z
    .union([z.enum(["supportive", "steady", "tense"]), z.null()])
    .optional(),
  disabled: z.boolean(),
  isCurrentMonth: z.boolean(),
  isToday: z.boolean(),
  lunar: CalendarLunarFields.optional(),
});
export const CalendarMeta = z.object({
  contractVersion: z.number().int(),
  generatedAt: z.string(),
  schemaVersion: z.literal("calendar/v1"),
});
export const CalendarPayload = z.object({
  allowedRange: AllowedRange,
  days: z.array(CalendarDay),
  meta: CalendarMeta,
  month: z.string(),
  title: z.string(),
});
export const CheckinCreate = z.object({
  accuracy: z
    .union([z.union([z.literal(1), z.literal(2), z.literal(3)]), z.null()])
    .optional(),
  energy: z
    .union([
      z.union([
        z.literal(1),
        z.literal(2),
        z.literal(3),
        z.literal(4),
        z.literal(5),
      ]),
      z.null(),
    ])
    .optional(),
  mood: z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
  ]),
  note: z.union([z.string(), z.null()]).optional(),
  tags: z.array(z.string()).optional(),
  targetDate: z.string(),
});
export const CheckinMetrics = z.object({
  accuracyDistribution: z.record(z.number().int()),
  averageAccuracy: z.union([z.number(), z.null()]),
  averageEnergy: z.union([z.number(), z.null()]),
  averageMood: z.number(),
  currentStreak: z.number().int().gte(0),
  longestStreak: z.number().int().gte(0),
  moodDistribution: z.record(z.number().int()),
  tagFrequency: z.record(z.number().int()),
  totalCheckins: z.number().int().gte(0),
});
export const CheckinResponse = z.object({
  accuracy: z.union([z.number(), z.null()]).optional(),
  createdAt: z.string().datetime({ offset: true }),
  energy: z.union([z.number(), z.null()]).optional(),
  filledAt: z.union([z.string(), z.null()]),
  id: z.number().int(),
  mood: z.number().int().gte(1).lte(5),
  note: z.union([z.string(), z.null()]),
  streak: z.number().int().gte(1),
  tags: z.array(z.string()),
  targetDate: z.string(),
});
export const ConvergenceEvidence = z.object({
  convergenceLevel: z.enum(["double", "triple", "quad", "peak"]),
  summary: z.string(),
  techniques: z.array(z.string()),
  theme: z.string(),
});
export const app__schemas__horary__ParagraphBlock = z.object({
  text: z.string(),
  type: z.literal("paragraph").default("paragraph"),
});
export const app__schemas__horary__LeadBlock = z.object({
  text: z.string(),
  type: z.literal("lead").default("lead"),
});
export const app__schemas__horary__HeadingBlock = z.object({
  level: z.union([z.literal(2), z.literal(3)]),
  text: z.string(),
  type: z.literal("heading").default("heading"),
});
export const app__schemas__horary__ListBlock = z.object({
  items: z.array(z.string()),
  style: z.union([z.enum(["bullet", "check"]), z.null()]).optional(),
  type: z.literal("list").default("list"),
});
export const app__schemas__horary__CalloutBlock = z.object({
  text: z.string(),
  title: z.union([z.string(), z.null()]).optional(),
  tone: z
    .union([z.enum(["neutral", "strength", "risk", "insight"]), z.null()])
    .optional(),
  type: z.literal("callout").default("callout"),
});
export const app__schemas__horary__ProsConsBlock = z.object({
  cons: z.union([z.array(z.string()), z.null()]).optional(),
  consLabel: z.union([z.string(), z.null()]).optional(),
  pros: z.union([z.array(z.string()), z.null()]).optional(),
  prosLabel: z.union([z.string(), z.null()]).optional(),
  type: z.literal("pros_cons").default("pros_cons"),
});
export const app__schemas__horary__DividerBlock = z.object({
  type: z.literal("divider").default("divider"),
});
export const app__schemas__horary__QuoteBlock = z.object({
  source: z.union([z.string(), z.null()]).optional(),
  text: z.string(),
  type: z.literal("quote").default("quote"),
});
export const VerdictCardBlock = z.object({
  confidence: z.number(),
  confidenceExplanation: z.string(),
  confidenceLabel: z.enum(["low", "medium", "high"]),
  label: z.union([z.string(), z.null()]).optional(),
  type: z.literal("verdict_card").default("verdict_card"),
  verdict: z.enum(["yes", "no", "maybe"]),
});
export const TestimonyItem = z.object({
  aspectType: z.union([z.string(), z.null()]).optional(),
  explanation: z.string(),
  orb: z.union([z.number(), z.null()]).optional(),
  planets: z.array(z.string()).optional(),
  title: z.string(),
  weight: z.number(),
});
export const TestimoniesBlock = z.object({
  cons: z.array(TestimonyItem).optional(),
  consLabel: z.string().optional().default("Свидетельства «против»"),
  neutral: z.array(TestimonyItem).optional(),
  neutralLabel: z.string().optional().default("Нейтральные факторы"),
  pros: z.array(TestimonyItem).optional(),
  prosLabel: z.string().optional().default("Свидетельства «за»"),
  type: z.literal("testimonies").default("testimonies"),
});
export const TimingBlock = z.object({
  status: z.enum(["known", "unclear", "not_enough_evidence"]),
  text: z.string(),
  timeRange: z.union([z.string(), z.null()]).optional(),
  type: z.literal("timing").default("timing"),
});
export const HoraryAnswerRead = z.object({
  blocks: z.array(
    z.discriminatedUnion("type", [
      app__schemas__horary__ParagraphBlock,
      app__schemas__horary__LeadBlock,
      app__schemas__horary__HeadingBlock,
      app__schemas__horary__ListBlock,
      app__schemas__horary__CalloutBlock,
      app__schemas__horary__ProsConsBlock,
      app__schemas__horary__DividerBlock,
      app__schemas__horary__QuoteBlock,
      VerdictCardBlock,
      TestimoniesBlock,
      TimingBlock,
    ])
  ),
  confidence: z.number(),
  confidenceExplanation: z.string().optional().default(""),
  confidenceLabel: z
    .enum(["low", "medium", "high"])
    .optional()
    .default("medium"),
  generatedAt: z.string(),
  planets: z.array(z.string()),
  verdict: z.enum(["yes", "no", "maybe"]),
});
export const HoraryQuestionCreate = z.object({
  category: z
    .union([
      z.enum(["love", "career", "money", "health", "travel", "other"]),
      z.null(),
    ])
    .optional(),
  clientLocalTime: z.union([z.string(), z.null()]).optional(),
  clientTimezone: z.string().max(100),
  idempotencyKey: z.string().min(1).max(255),
  questionLat: z.union([z.number(), z.null()]).optional(),
  questionLocationName: z.union([z.string(), z.null()]).optional(),
  questionLon: z.union([z.number(), z.null()]).optional(),
  text: z.string().min(5).max(500),
});
export const HoraryChartAspect = z.object({
  aspectType: z.string(),
  orb: z.number(),
  planet: z.string(),
  targetPlanet: z.string(),
});
export const HoraryChartHouse = z.object({
  cusp: z.number(),
  number: z.number().int(),
  sign: z.union([z.string(), z.null()]).optional(),
});
export const HoraryChartPlanet = z.object({
  latitude: z.union([z.number(), z.null()]).optional(),
  longitude: z.number(),
  name: z.string(),
  sign: z.union([z.string(), z.null()]).optional(),
  speed: z.union([z.number(), z.null()]).optional(),
});
export const HoraryChartSnapshot = z.object({
  aspects: z.array(HoraryChartAspect),
  castAt: z.string(),
  houseSystem: z.union([z.string(), z.null()]).optional(),
  houses: z.array(HoraryChartHouse),
  latitude: z.number(),
  locationName: z.union([z.string(), z.null()]).optional(),
  longitude: z.number(),
  planets: z.array(HoraryChartPlanet),
  source: z.literal("solarsage"),
  timezone: z.string(),
});
export const HoraryQuestionRead = z.object({
  answer: z.union([HoraryAnswerRead, z.null()]).optional(),
  category: z.union([z.string(), z.null()]),
  chart: z.union([HoraryChartSnapshot, z.null()]),
  clientLocalTime: z.union([z.string(), z.null()]),
  clientTimezone: z.string(),
  createdAt: z.string(),
  creditRefunded: z.boolean().optional().default(false),
  failureStage: z.union([z.string(), z.null()]).optional(),
  id: z.string(),
  publicErrorCode: z.union([z.string(), z.null()]).optional(),
  publicErrorMessage: z.union([z.string(), z.null()]).optional(),
  questionLocationName: z.union([z.string(), z.null()]).optional(),
  spentCreditSource: z
    .union([
      z.enum([
        "subscription_weekly_free",
        "referral_bonus",
        "gift",
        "paid",
        "adjustment",
      ]),
      z.null(),
    ])
    .optional(),
  status: z.enum([
    "pending",
    "processing",
    "answered",
    "failed",
    "refunded",
    "expired",
  ]),
  text: z.string(),
});
export const HoraryQuotaRead = z.object({
  bonusCredits: z.number().int(),
  canPurchase: z.boolean().optional().default(false),
  nextWeeklyFreeAt: z.union([z.string(), z.null()]).optional(),
  paidCredits: z.number().int(),
  weeklyFreeAvailable: z.boolean(),
  weeklyFreeExpiresAt: z.union([z.string(), z.null()]).optional(),
});
export const LocationData = z
  .object({
    city: z.union([z.string(), z.null()]),
    lat: z.union([z.number(), z.null()]),
    lon: z.union([z.number(), z.null()]),
    tz: z.union([z.string(), z.null()]),
  })
  .partial();
export const PersonBirth = z.object({
  date: z.string(),
  place: z.union([z.string(), z.null()]).optional(),
  time: z.union([z.string(), z.null()]).optional(),
});
export const Person = z
  .object({
    birth: z.union([PersonBirth, z.null()]),
    name: z.union([z.string(), z.null()]),
  })
  .partial();
export const NatalMeta = z.object({
  calculationVersion: z.union([z.number(), z.null()]).optional(),
  contractVersion: z.number().int(),
  generatedAt: z.string(),
  interpretationVersion: z.union([z.number(), z.null()]).optional(),
  person: z.union([Person, z.null()]).optional(),
  schemaVersion: z.literal("natal/v1"),
  subtitle: z.union([z.string(), z.null()]).optional(),
  title: z.string(),
});
export const app__schemas__natal__ParagraphBlock = z.object({
  text: z.string(),
  type: z.literal("paragraph"),
});
export const app__schemas__natal__LeadBlock = z.object({
  text: z.string(),
  type: z.literal("lead"),
});
export const app__schemas__natal__HeadingBlock = z.object({
  level: z.number().int().optional().default(2),
  text: z.string(),
  type: z.literal("heading"),
});
export const app__schemas__natal__ListBlock = z.object({
  items: z.array(z.string()),
  ordered: z.boolean().optional().default(false),
  type: z.literal("list"),
});
export const app__schemas__natal__CalloutBlock = z.object({
  text: z.string(),
  title: z.union([z.string(), z.null()]).optional(),
  tone: z
    .enum(["info", "warning", "insight", "positive"])
    .optional()
    .default("info"),
  type: z.literal("callout"),
});
export const ProsConsItem = z.object({ text: z.string(), title: z.string() });
export const app__schemas__natal__ProsConsBlock = z.object({
  cons: z.array(ProsConsItem).optional().default([]),
  consLabel: z.string().optional().default("Зоны роста"),
  pros: z.array(ProsConsItem).optional().default([]),
  prosLabel: z.string().optional().default("Сильные стороны"),
  type: z.literal("pros_cons"),
});
export const app__schemas__natal__QuoteBlock = z.object({
  source: z.union([z.string(), z.null()]).optional(),
  text: z.string(),
  type: z.literal("quote"),
});
export const app__schemas__natal__DividerBlock = z.object({
  type: z.literal("divider"),
});
export const HighlightItem = z.object({
  id: z.string(),
  text: z.string(),
  title: z.string(),
  tone: z.union([z.string(), z.null()]).optional(),
});
export const HighlightsBlock = z.object({
  items: z.array(HighlightItem),
  type: z.literal("highlights"),
});
export const BulletsBlock = z.object({
  items: z.array(z.string()),
  type: z.literal("bullets"),
});
export const NatalSection = z.object({
  blocks: z.array(
    z.discriminatedUnion("type", [
      app__schemas__natal__ParagraphBlock,
      app__schemas__natal__LeadBlock,
      app__schemas__natal__HeadingBlock,
      app__schemas__natal__ListBlock,
      app__schemas__natal__CalloutBlock,
      app__schemas__natal__ProsConsBlock,
      app__schemas__natal__QuoteBlock,
      app__schemas__natal__DividerBlock,
      HighlightsBlock,
      BulletsBlock,
    ])
  ),
  iconName: z.union([z.string(), z.null()]).optional(),
  id: z.string(),
  summary: z.union([z.string(), z.null()]).optional(),
  title: z.string(),
});
export const NatalPayload = z.object({
  meta: NatalMeta,
  sections: z.array(NatalSection),
});
export const ProductRead = z.object({
  currency: z.string(),
  description: z.union([z.string(), z.null()]).optional(),
  horaryQuota: z.union([z.number(), z.null()]).optional(),
  name: z.string(),
  periodDays: z.union([z.number(), z.null()]).optional(),
  priceKopecks: z.number().int(),
  productType: z.enum(["subscription_recurrent", "one_time"]),
  slug: z.string(),
});
export const ProductsListResponse = z.object({
  products: z.array(ProductRead),
});
export const ProfileRead = z.object({
  birth: BirthData,
  birthdayLocation: z.union([LocationData, z.null()]).optional(),
  currentLocation: z.union([LocationData, z.null()]).optional(),
  firstName: z.union([z.string(), z.null()]).optional(),
  gender: z.union([z.enum(["male", "female"]), z.null()]).optional(),
  isOnboarded: z.boolean().optional().default(false),
  userId: z.string().uuid(),
});
export const ProfileWrite = z
  .object({
    birth: BirthData,
    birthdayLocation: z.union([LocationData, z.null()]),
    currentLocation: z.union([LocationData, z.null()]),
    firstName: z.union([z.string(), z.null()]),
    gender: z.union([z.enum(["male", "female"]), z.null()]),
  })
  .partial();
export const PurchaseStartResponse = z.object({
  confirmationUrl: z.union([z.string(), z.null()]).optional(),
  productSlug: z.string(),
  providerPaymentId: z.string(),
  purchaseId: z.string().uuid(),
  status: z.string(),
});
export const PurchaseStatusResponse = z.object({
  confirmationUrl: z.union([z.string(), z.null()]).optional(),
  productSlug: z.string(),
  providerPaymentId: z.union([z.string(), z.null()]).optional(),
  purchaseId: z.string().uuid(),
  status: z.string(),
});
export const SphereContribution = z.object({
  after: z.union([z.number(), z.null()]).optional(),
  amount: z.number(),
  before: z.union([z.number(), z.null()]).optional(),
  evidence: z.string(),
  source: z.enum(["base_signal", "activation", "convergence", "cap"]),
  sourceId: z.string(),
  sphere: z.string(),
});
export const SphereScoreV2 = z.object({
  activationScore: z.number(),
  baseScore: z.number(),
  contributions: z.array(SphereContribution),
  convergenceBonus: z.number(),
  dominanceCapped: z.boolean().optional().default(false),
  finalScore: z.number(),
  key: z.string(),
  normalizedScore: z.union([z.number(), z.null()]).optional(),
  rawScore: z.number(),
  title: z.string(),
});
export const ScoringV2Result = z.object({
  canonVersions: z.record(z.string()),
  dayStatus: z.string(),
  debug: z.object({}).partial().passthrough().optional(),
  scoringVersion: z.string().optional().default("ss-scoring-2.0"),
  sphereScores: z.record(SphereScoreV2),
  statusBreakdown: z.object({}).partial().passthrough(),
  topActivations: z.array(ActivationEvidence),
  topSignals: z.array(z.object({}).partial().passthrough()),
});
export const SubscriptionStartResponse = z.object({
  confirmationUrl: z.union([z.string(), z.null()]).optional(),
  productSlug: z.string(),
  providerPaymentId: z.string(),
  status: z.string(),
  subscriptionId: z.string().uuid(),
});
export const SubscriptionStatusResponse = z.object({
  accessUntil: z.union([z.string(), z.null()]).optional(),
  cancelable: z.boolean().optional().default(false),
  currency: z.union([z.string(), z.null()]).optional(),
  currentPeriodEnd: z.union([z.string(), z.null()]).optional(),
  hasAccess: z.boolean(),
  nextChargeAt: z.union([z.string(), z.null()]).optional(),
  priceKopecks: z.union([z.number(), z.null()]).optional(),
  productSlug: z.union([z.string(), z.null()]).optional(),
  renewing: z.boolean().optional().default(false),
  status: z.enum([
    "none",
    "pending",
    "active",
    "past_due",
    "canceled",
    "expired",
  ]),
  subscriptionId: z.union([z.string(), z.null()]).optional(),
});
export const TelegramAuthRequest = z.object({
  initData: z.string().min(1).max(8192),
});
export const TodayAction = z.object({
  href: z.union([z.string(), z.null()]).optional(),
  id: z.string(),
  label: z.string(),
});
export const ConcreteAdviceCounts = z.object({
  avoid: z.number().int(),
  caution: z.number().int(),
  good: z.number().int(),
  neutral: z.number().int(),
});
export const ConcreteAdviceEvidence = z.object({
  activationId: z.union([z.string(), z.null()]).optional(),
  aspectType: z.union([z.string(), z.null()]).optional(),
  contributionSourceId: z.union([z.string(), z.null()]).optional(),
  house: z.union([z.number(), z.null()]).optional(),
  kind: z.enum([
    "sphere_score",
    "aspect",
    "planet_in_house",
    "day_status",
    "lunar",
    "important_today",
    "activation",
    "score_contribution",
  ]),
  orb: z.union([z.number(), z.null()]).optional(),
  planet: z.union([z.string(), z.null()]).optional(),
  sign: z.union([z.string(), z.null()]).optional(),
  sourceFrame: z.union([z.string(), z.null()]).optional(),
  sphereKey: z.union([z.string(), z.null()]).optional(),
  strength: z.union([z.number(), z.null()]).optional(),
  targetFrame: z.union([z.string(), z.null()]).optional(),
  targetPlanet: z.union([z.string(), z.null()]).optional(),
  technique: z.union([z.string(), z.null()]).optional(),
  techniqueFamily: z.union([z.string(), z.null()]).optional(),
  title: z.string(),
  weight: z.union([z.number(), z.null()]).optional(),
});
export const ConcreteAdviceRow = z.object({
  confidence: z.enum(["high", "medium", "low"]),
  evidence: z.array(ConcreteAdviceEvidence),
  iconName: z.string(),
  key: z.enum([
    "work",
    "money",
    "documents",
    "relationships",
    "sport",
    "communication",
    "health",
    "decisions",
    "travel",
    "creativity",
    "study",
    "shopping",
  ]),
  label: z.string(),
  rank: z.number().int(),
  text: z.string(),
  verdict: z.enum(["good", "caution", "avoid", "neutral"]),
});
export const ConcreteAdviceBlock = z.object({
  counts: ConcreteAdviceCounts,
  rows: z.array(ConcreteAdviceRow),
});
export const DayChartAspect = z.object({
  aspectType: z.string(),
  orb: z.union([z.number(), z.null()]).optional(),
  planet: z.string(),
  strength: z.union([z.number(), z.null()]).optional(),
  targetPlanet: z.string(),
});
export const DayChartHouse = z.object({
  cuspLongitude: z.number(),
  number: z.number().int(),
  sign: z.union([z.string(), z.null()]).optional(),
});
export const DayChartTransitPlanet = z.object({
  house: z.union([z.number(), z.null()]).optional(),
  interpretation: z.union([z.string(), z.null()]).optional(),
  longitude: z.number(),
  motion: z
    .union([z.enum(["direct", "retrograde", "stationary"]), z.null()])
    .optional(),
  name: z.string(),
  retrograde: z.union([z.boolean(), z.null()]).optional(),
  sign: z.union([z.string(), z.null()]).optional(),
  speed: z.union([z.number(), z.null()]).optional(),
});
export const DayChart = z.object({
  aspects: z.array(DayChartAspect),
  houses: z.array(DayChartHouse),
  source: z.literal("solarsage"),
  transitPlanets: z.array(DayChartTransitPlanet),
});
export const DayQuality = z.object({
  frictionScore: z.number(),
  intensityScore: z.number(),
  supportScore: z.number(),
});
export const DaySummaryFact = z.object({
  iconName: z.string(),
  kind: z.enum(["top_planet", "lunar_phase", "void_moon", "top_flag"]),
  summary: z.union([z.string(), z.null()]).optional(),
  title: z.string(),
});
export const DaySummaryBlock = z.object({
  facts: z.array(DaySummaryFact),
  statusLabel: z.string(),
  statusLine: z.string(),
});
export const TodayImportantEvent = z.object({
  endsAt: z.union([z.string(), z.null()]).optional(),
  exactAt: z.union([z.string(), z.null()]).optional(),
  id: z.string(),
  kind: z.enum([
    "void_moon",
    "new_moon",
    "full_moon",
    "solar_eclipse",
    "lunar_eclipse",
    "mercury_retrograde",
    "mercury_station",
    "moon_quarter",
    "sun_ingress",
    "fast_planet_aspect",
  ]),
  localTimeLabel: z.union([z.string(), z.null()]).optional(),
  priority: z.number().int().optional().default(5),
  startsAt: z.union([z.string(), z.null()]).optional(),
  summary: z.string(),
  timezone: z.string(),
  title: z.string(),
  tone: z.enum(["supportive", "caution", "neutral_shift"]),
});
export const ManifestationZone = z.object({
  description: z.string(),
  house: z.number().int(),
  intensity: z.enum(["background", "active", "peak"]),
  theme: z.string(),
});
export const TodayMeta = z.object({
  activationLayerVersion: z
    .union([z.number(), z.string(), z.null()])
    .optional(),
  auditTraceId: z.union([z.string(), z.null()]).optional(),
  cached: z.boolean().optional().default(false),
  calculationVersion: z.union([z.number(), z.string()]),
  canonVersions: z.union([z.record(z.string()), z.null()]).optional(),
  contentVersion: z.number().int(),
  contractVersion: z.number().int(),
  frontendPayloadVersion: z.number().int().optional().default(1),
  generatedAt: z.string(),
  normalizationVersion: z.number().int(),
  payloadVersion: z
    .enum(["today.v1", "today.v2", "today.v2.1"])
    .optional()
    .default("today.v1"),
  promptVersion: z.number().int(),
  schemaVersion: z.literal("today/v1"),
  scoringCanonVersion: z.union([z.number(), z.null()]).optional(),
  scoringVersion: z.union([z.number(), z.string()]),
});
export const MicrocopyItem = z.object({
  id: z.string(),
  scope: z.enum(["today", "morning", "evening"]),
  textLong: z.string(),
  textShort: z.string(),
  tone: z.array(z.enum(["bold", "supportive", "gentle", "warning"])),
});
export const PeriodContext = z
  .object({
    activePeriod: z.union([z.string(), z.null()]),
    longTermTransit: z.union([z.string(), z.null()]),
    solarReturnEmphasis: z.union([z.string(), z.null()]),
    yearRuler: z.union([z.string(), z.null()]),
    yearTheme: z.union([z.string(), z.null()]),
  })
  .partial();
export const PlanetInfluence = z.object({
  name: z.string(),
  rank: z.number().int(),
  score: z.number(),
});
export const ReadingBody = z.object({ paragraphs: z.array(z.string()) });
export const SphereScore = z.object({
  key: z.string(),
  rank: z.number().int(),
  score: z.number(),
});
export const TopFlagHint = z
  .object({
    howItFeels: z.union([z.string(), z.null()]),
    whyToday: z.union([z.string(), z.null()]),
  })
  .partial();
export const TopFlag = z.object({
  hint: z.union([TopFlagHint, z.null()]).optional(),
  iconName: z.string(),
  summary: z.string(),
  title: z.string(),
});
export const TodayV2ActivatedTarget = z.object({
  activationIds: z.array(z.string()),
  familyCount: z.number().int(),
  label: z.string(),
  spheres: z.array(z.string()),
  targetKey: z.string(),
  targetType: z.enum(["planet", "house", "lot", "angle", "sphere"]),
  techniques: z.array(z.string()),
});
export const TodayV2ActivationSummary = z.object({
  headline: z.string(),
  topActivatedTargets: z.array(TodayV2ActivatedTarget),
});
export const TodayV2HorizonPipelineAuditBuilt = z.object({
  reason: z.literal("selected"),
  schemaVersion: z
    .literal("today-horizon-pipeline-audit.v1")
    .optional()
    .default("today-horizon-pipeline-audit.v1"),
  selectedCount: z.literal(3),
  status: z.literal("built"),
});
export const TodayV2HorizonPipelineAuditUnavailable = z.object({
  reason: z.enum([
    "invalid_target_clock",
    "missing_long",
    "missing_medium",
    "missing_fast",
    "no_coherent_triple",
  ]),
  schemaVersion: z
    .literal("today-horizon-pipeline-audit.v1")
    .optional()
    .default("today-horizon-pipeline-audit.v1"),
  selectedCount: z.literal(0),
  status: z.literal("unavailable"),
});
export const TodayV2Audit = z.object({
  activationLayerVersion: z
    .union([z.string(), z.number(), z.null()])
    .optional(),
  available: z.boolean().optional().default(false),
  calculationVersion: z.union([z.string(), z.number()]),
  canonVersions: z.record(z.string()).optional(),
  horizonPipeline: z
    .union([
      z.discriminatedUnion("status", [
        TodayV2HorizonPipelineAuditBuilt,
        TodayV2HorizonPipelineAuditUnavailable,
      ]),
      z.null(),
    ])
    .optional(),
  payloadVersion: z.string(),
  scoringVersion: z.union([z.string(), z.number()]),
  traceId: z.union([z.string(), z.null()]).optional(),
  v1V2Diff: z
    .union([z.object({}).partial().passthrough(), z.null()])
    .optional(),
});
export const TodayV2HorizonIntro = z.object({
  activationIds: z.array(z.string().min(1).max(160)).min(1),
  body: z.string().min(1).max(1200),
  eyebrow: z.string().min(1).max(160),
  headline: z.string().min(1).max(240),
  themeKey: z.string().min(1).max(160),
});
export const TodayV2Provenance = z
  .object({
    activationIds: z.array(z.string().min(1).max(160)),
    natalFactIds: z.array(
      z
        .string()
        .min(2)
        .max(128)
        .regex(/^[a-z0-9][a-z0-9._:-]{1,127}$/)
    ),
    profileFactIds: z.array(
      z
        .string()
        .min(2)
        .max(128)
        .regex(/^[a-z0-9][a-z0-9._:-]{1,127}$/)
    ),
    sphereKeys: z.array(
      z.enum([
        "work",
        "money",
        "documents",
        "relationships",
        "sport",
        "communication",
        "health",
        "decisions",
        "travel",
        "creativity",
        "study",
        "shopping",
      ])
    ),
  })
  .partial();
export const TodayV2GroundedItem = z.object({
  conditional: z.boolean().optional().default(false),
  id: z.string().min(1).max(160),
  kind: z.enum([
    "explanation",
    "strength",
    "risk",
    "manifestation",
    "action",
    "avoid",
    "technique_definition",
  ]),
  provenance: TodayV2Provenance,
  text: z.string().min(1).max(1200),
});
export const TodayV2HorizonActions = z.object({
  avoid: z.array(TodayV2GroundedItem).min(1),
  do: z.array(TodayV2GroundedItem).min(1),
  heading: z.string().min(1).max(160),
  validUntil: z.string(),
  validUntilLabel: z.string().min(1).max(160),
});
export const TodayV2Manifestation = z.object({
  body: z.string().min(1).max(1200),
  condition: z.union([z.string(), z.null()]).optional(),
  id: z.string().min(1).max(160),
  provenance: TodayV2Provenance,
  sphereKeys: z
    .array(
      z.enum([
        "work",
        "money",
        "documents",
        "relationships",
        "sport",
        "communication",
        "health",
        "decisions",
        "travel",
        "creativity",
        "study",
        "shopping",
      ])
    )
    .min(1)
    .max(3),
  title: z.string().min(1).max(240),
});
export const TodayV2HorizonTiming = z.object({
  activeFrom: z.string(),
  activeUntil: z.string(),
  exactAt: z.union([z.string(), z.null()]).optional(),
  peakLabel: z.union([z.string(), z.null()]).optional(),
  precision: z.enum(["date", "instant"]),
  rangeLabel: z.string().min(1).max(160),
  state: z.enum([
    "upcoming",
    "building",
    "active",
    "exact",
    "peaked",
    "fading",
    "background",
  ]),
  stateLabel: z.string().min(1).max(160),
  timezone: z.string().min(1).max(80),
});
export const TodayV2TechniqueExplanation = z.object({
  activationIds: z.array(z.string().min(1).max(160)).min(1),
  label: z.string().min(1).max(160),
  technique: z.string().min(1).max(160),
  timing: z.union([TodayV2HorizonTiming, z.null()]).optional(),
  whatItIs: z.string().min(1).max(1200),
  whyItMattersNow: z.string().min(1).max(1200),
});
export const TodayV2Horizon = z.object({
  actions: TodayV2HorizonActions,
  activationIds: z.array(z.string().min(1).max(160)).min(1),
  eyebrow: z.string().min(1).max(160),
  horizon: z.enum(["long", "medium", "fast"]),
  id: z.string().min(1).max(160),
  likelySpheres: z
    .array(
      z.enum([
        "work",
        "money",
        "documents",
        "relationships",
        "sport",
        "communication",
        "health",
        "decisions",
        "travel",
        "creativity",
        "study",
        "shopping",
      ])
    )
    .min(1)
    .max(3),
  manifestations: z.array(TodayV2Manifestation).min(1).max(3),
  plainExplanation: z.string().min(1).max(1200),
  risk: z.union([TodayV2GroundedItem, z.null()]).optional(),
  strength: z.union([TodayV2GroundedItem, z.null()]).optional(),
  summary: z.string().min(1).max(1200),
  techniqueExplanations: z.array(TodayV2TechniqueExplanation).min(1),
  timing: TodayV2HorizonTiming,
  title: z.string().min(1).max(240),
  tone: z.enum(["supportive", "neutral", "tense", "mixed"]),
});
export const TodayV2HorizonsBlock = z.object({
  guidanceMode: z.enum(["deterministic", "llm_refined"]),
  intro: TodayV2HorizonIntro,
  items: z.array(TodayV2Horizon).min(3).max(3),
  schemaVersion: z.literal("today-horizons.v1"),
  warnings: z.array(z.string().min(1).max(160)).optional(),
});
export const TodayV2WhyTodayItem = z.object({
  activationIds: z.array(z.string()),
  body: z.string(),
  id: z.string(),
  techniques: z.array(z.string()),
  title: z.string(),
});
export const TodayV2Block = z.object({
  activationEvidence: z.array(ActivationEvidence),
  activationSummary: TodayV2ActivationSummary,
  audit: TodayV2Audit,
  horizons: z.union([TodayV2HorizonsBlock, z.null()]).optional(),
  scoreBreakdown: z.record(SphereScoreV2),
  whyToday: z.array(TodayV2WhyTodayItem),
});
export const WeekStripDay = z.object({
  date: z.string(),
  dayStatus: z.enum(["supportive", "steady", "tense"]),
  isToday: z.boolean(),
});
export const WhyParagraph = z.object({
  kind: z.literal("paragraph"),
  text: z.string(),
});
export const WhyBullets = z.object({
  items: z.array(z.string()),
  kind: z.literal("bullets"),
});
export const WhySection = z.object({
  aspects: z.union([z.array(z.string()), z.null()]).optional(),
  blocks: z.array(z.union([WhyParagraph, WhyBullets])),
  houses: z.union([z.array(z.number().int()), z.null()]).optional(),
  iconName: z.union([z.string(), z.null()]).optional(),
  id: z.string(),
  layer: z
    .union([
      z.enum([
        "main_theme",
        "daily_layer",
        "personal_activation",
        "period_background",
        "amplifiers",
        "softeners",
        "manifestation_zones",
        "astrological_meaning",
        "practical_meaning",
      ]),
      z.null(),
    ])
    .optional(),
  planets: z.union([z.array(z.string()), z.null()]).optional(),
  techniques: z.union([z.array(z.string()), z.null()]).optional(),
  title: z.string(),
});
export const WhyThisHappens = z.object({ sections: z.array(WhySection) });
export const YesterdayEcho = z.object({
  accuracy: z
    .union([
      z.union([
        z.literal(1),
        z.literal(2),
        z.literal(3),
        z.literal(4),
        z.literal(5),
      ]),
      z.null(),
    ])
    .optional(),
  closureText: z.string(),
  hadCheckin: z.boolean(),
  mood: z
    .union([
      z.union([
        z.literal(1),
        z.literal(2),
        z.literal(3),
        z.literal(4),
        z.literal(5),
      ]),
      z.null(),
    ])
    .optional(),
  transition: z.enum(["released", "intensified", "shifted", "continued"]),
});
export const TodayPayload = z.object({
  access: ContentAccessState,
  actions: z.union([z.array(TodayAction), z.null()]).optional(),
  activationEvidence: z
    .union([z.array(ConvergenceEvidence), z.null()])
    .optional(),
  concreteAdvice: ConcreteAdviceBlock,
  date: z.string(),
  dayChart: z.union([DayChart, z.null()]).optional(),
  dayQuality: z.union([DayQuality, z.null()]).optional(),
  dayStatus: z.enum(["supportive", "steady", "tense"]),
  daySummary: DaySummaryBlock,
  headline: z.string(),
  importantToday: z.array(TodayImportantEvent).optional().default([]),
  manifestationZones: z
    .union([z.array(ManifestationZone), z.null()])
    .optional(),
  meta: TodayMeta,
  microcopy: z.array(MicrocopyItem),
  notes: z.union([z.string(), z.null()]).optional(),
  periodContext: z.union([PeriodContext, z.null()]).optional(),
  planetInfluences: z.union([z.array(PlanetInfluence), z.null()]).optional(),
  reading: ReadingBody,
  sphereScores: z.union([z.array(SphereScore), z.null()]).optional(),
  subtitle: z.union([z.string(), z.null()]).optional(),
  title: z.string(),
  topFlags: z.array(TopFlag),
  v2: z.union([TodayV2Block, z.null()]).optional(),
  weekStrip: z.array(WeekStripDay),
  whyThisHappens: WhyThisHappens,
  yesterdayEcho: z.union([YesterdayEcho, z.null()]).optional(),
});
export const YesterdayCheckinResponse = z.object({
  checkin: z.union([CheckinResponse, z.null()]),
  hadCheckin: z.boolean(),
});
// END_BLOCK: SCHEMA_DECLARATIONS

// START_BLOCK: SCHEMA_MAP
export const schemas = {
  AccessSummary,
  ActivationEvidence,
  ActivationLayer,
  AuthError,
  AuthSession,
  BirthData,
  AllowedRange,
  ContentAccessState,
  CalendarLunarFields,
  CalendarDay,
  CalendarMeta,
  CalendarPayload,
  CheckinCreate,
  CheckinMetrics,
  CheckinResponse,
  ConvergenceEvidence,
  app__schemas__horary__ParagraphBlock,
  app__schemas__horary__LeadBlock,
  app__schemas__horary__HeadingBlock,
  app__schemas__horary__ListBlock,
  app__schemas__horary__CalloutBlock,
  app__schemas__horary__ProsConsBlock,
  app__schemas__horary__DividerBlock,
  app__schemas__horary__QuoteBlock,
  VerdictCardBlock,
  TestimonyItem,
  TestimoniesBlock,
  TimingBlock,
  HoraryAnswerRead,
  HoraryQuestionCreate,
  HoraryChartAspect,
  HoraryChartHouse,
  HoraryChartPlanet,
  HoraryChartSnapshot,
  HoraryQuestionRead,
  HoraryQuotaRead,
  LocationData,
  PersonBirth,
  Person,
  NatalMeta,
  app__schemas__natal__ParagraphBlock,
  app__schemas__natal__LeadBlock,
  app__schemas__natal__HeadingBlock,
  app__schemas__natal__ListBlock,
  app__schemas__natal__CalloutBlock,
  ProsConsItem,
  app__schemas__natal__ProsConsBlock,
  app__schemas__natal__QuoteBlock,
  app__schemas__natal__DividerBlock,
  HighlightItem,
  HighlightsBlock,
  BulletsBlock,
  NatalSection,
  NatalPayload,
  ProductRead,
  ProductsListResponse,
  ProfileRead,
  ProfileWrite,
  PurchaseStartResponse,
  PurchaseStatusResponse,
  SphereContribution,
  SphereScoreV2,
  ScoringV2Result,
  SubscriptionStartResponse,
  SubscriptionStatusResponse,
  TelegramAuthRequest,
  TodayAction,
  ConcreteAdviceCounts,
  ConcreteAdviceEvidence,
  ConcreteAdviceRow,
  ConcreteAdviceBlock,
  DayChartAspect,
  DayChartHouse,
  DayChartTransitPlanet,
  DayChart,
  DayQuality,
  DaySummaryFact,
  DaySummaryBlock,
  TodayImportantEvent,
  ManifestationZone,
  TodayMeta,
  MicrocopyItem,
  PeriodContext,
  PlanetInfluence,
  ReadingBody,
  SphereScore,
  TopFlagHint,
  TopFlag,
  TodayV2ActivatedTarget,
  TodayV2ActivationSummary,
  TodayV2HorizonPipelineAuditBuilt,
  TodayV2HorizonPipelineAuditUnavailable,
  TodayV2Audit,
  TodayV2HorizonIntro,
  TodayV2Provenance,
  TodayV2GroundedItem,
  TodayV2HorizonActions,
  TodayV2Manifestation,
  TodayV2HorizonTiming,
  TodayV2TechniqueExplanation,
  TodayV2Horizon,
  TodayV2HorizonsBlock,
  TodayV2WhyTodayItem,
  TodayV2Block,
  WeekStripDay,
  WhyParagraph,
  WhyBullets,
  WhySection,
  WhyThisHappens,
  YesterdayEcho,
  TodayPayload,
  YesterdayCheckinResponse,
};
// END_BLOCK: SCHEMA_MAP
