// ############################################################################
// AI_HEADER: MODULE_CONTRACTS_BARREL
// ROLE: Public re-export of generated contract types. The frontend MUST import
//   payload types only from this barrel ("@/packages/contracts").
// DEPENDENCIES: ./_generated (autogenerated by scripts/contracts/generate.sh)
// GRACE_ANCHORS: [BARREL_REEXPORT]
// ############################################################################

// START_MODULE_CONTRACT: M-WEB-CONTRACTS.barrel
// purpose: Provide the single import surface for typed contract payloads on the
//   frontend. Enforces W-1.1B Option B (Pydantic SoT) on the consumer side.
// owns:
//   - packages/contracts/index.ts
// inputs:
//   - packages/contracts/_generated.ts (autogenerated, do not edit)
// outputs:
//   - named type aliases: TodayPayload, NatalPayload, CalendarPayload,
//     ReadingBody, AccessSummary
// dependencies:
//   - openapi-typescript output
// side_effects:
//   - none
// invariants:
//   - MUST re-export only types from _generated.ts
//   - MUST NOT declare new shapes locally
//   - any shape addition goes through Pydantic + contracts:generate
// failure_policy:
//   - drift gate (W-1.1B) catches divergence between Pydantic and _generated.ts
// non_goals:
//   - runtime values, zod schemas, validators, request helpers
// END_MODULE_CONTRACT: M-WEB-CONTRACTS.barrel

// START_MODULE_MAP: M-WEB-CONTRACTS.barrel
// public_entrypoints:
//   - TodayPayload, NatalPayload, CalendarPayload, ReadingBody, AccessSummary
// semantic_blocks:
//   - BARREL_REEXPORT
// owned_tests:
//   - scripts/grace/check-negative.sh (foreign-import + local-redeclare cases)
// END_MODULE_MAP: M-WEB-CONTRACTS.barrel

// START_BLOCK: BARREL_REEXPORT
import type { components } from "./_generated";

export type TodayPayload = components["schemas"]["TodayPayload"];
export type NatalPayload = components["schemas"]["NatalPayload"];
export type CalendarPayload = components["schemas"]["CalendarPayload"];
export type ReadingBody = components["schemas"]["ReadingBody"];
export type AccessSummary = components["schemas"]["AccessSummary"];
export type ContentAccessState = components["schemas"]["ContentAccessState"];
export type TopFlag = components["schemas"]["TopFlag"];
export type WeekStripDay = components["schemas"]["WeekStripDay"];
export type TodayImportantEvent = components["schemas"]["TodayImportantEvent"];

// W-1.2: auth + profile surface.
export type TelegramAuthRequest = components["schemas"]["TelegramAuthRequest"];
export type AuthSession = components["schemas"]["AuthSession"];
export type AuthError = components["schemas"]["AuthError"];
export type BirthData = components["schemas"]["BirthData"];
export type ProfileRead = components["schemas"]["ProfileRead"];
export type ProfileWrite = components["schemas"]["ProfileWrite"];

// W-HORARY: Horary schemas
export type HoraryQuestionCreate = components["schemas"]["HoraryQuestionCreate"];
export type HoraryQuestionRead = components["schemas"]["HoraryQuestionRead"];
export type HoraryAnswerRead = components["schemas"]["HoraryAnswerRead"];
export type HoraryQuotaRead = components["schemas"]["HoraryQuotaRead"];
// END_BLOCK: BARREL_REEXPORT
