// ############################################################################
// AI_HEADER: MODULE_CONTRACTS_RUNTIME — handwritten barrel for runtime zod schemas.
// ROLE: Exports only stable, validated wire zod schemas generated from openapi.
// DEPENDENCIES: ./_generated.zod (autogenerated by scripts/contracts/generate.sh)
// ############################################################################

// START_MODULE_CONTRACT: M-WEB-CONTRACTS-RUNTIME
// purpose: Provide a handwritten barrel for generated runtime zod wire schemas.
// owns:
//   - packages/contracts/runtime.ts
// inputs:
//   - packages/contracts/_generated.zod.ts (autogenerated, do not edit)
// outputs:
//   - exports TodayPayloadWireSchema, TodayV2BlockWireSchema, ActivationEvidenceWireSchema
// dependencies:
//   - generated zod schemas
// side_effects: none
// emitted_logs: none
// invariants:
//   - exports only runtime zod validation schemas
//   - does not export any TypeScript-only types
// failure_policy: compile error on missing schema
// END_MODULE_CONTRACT: M-WEB-CONTRACTS-RUNTIME

// START_MODULE_MAP: M-WEB-CONTRACTS-RUNTIME
// public_entrypoints:
//   - TodayPayloadWireSchema
//   - TodayV2BlockWireSchema
//   - ActivationEvidenceWireSchema
// semantic_blocks:
//   - RUNTIME_EXPORTS
// owned_tests:
//   - __tests__/contracts/generated-runtime.test.ts
// END_MODULE_MAP: M-WEB-CONTRACTS-RUNTIME

// START_BLOCK: RUNTIME_EXPORTS
import {
  TodayPayload as TodayPayloadSchema,
  TodayV2Block as TodayV2BlockSchema,
  TodayV2HorizonsBlock as TodayV2HorizonsBlockSchema,
  TodayV2Horizon as TodayV2HorizonSchema,
  TodayV2HorizonTiming as TodayV2HorizonTimingSchema,
  TodayV2Provenance as TodayV2ProvenanceSchema,
  ActivationEvidence as ActivationEvidenceSchema,
  ProductsListResponse as ProductsListResponseSchema,
  SubscriptionStartResponse as SubscriptionStartResponseSchema,
  SubscriptionStatusResponse as SubscriptionStatusResponseSchema,
  PurchaseStartResponse as PurchaseStartResponseSchema,
  PurchaseStatusResponse as PurchaseStatusResponseSchema,
} from "./_generated.zod";

export const TodayPayloadWireSchema = TodayPayloadSchema;
export const TodayV2BlockWireSchema = TodayV2BlockSchema;
export const TodayV2HorizonsBlockWireSchema = TodayV2HorizonsBlockSchema;
export const TodayV2HorizonWireSchema = TodayV2HorizonSchema;
export const TodayV2HorizonTimingWireSchema = TodayV2HorizonTimingSchema;
export const TodayV2ProvenanceWireSchema = TodayV2ProvenanceSchema;
export const ActivationEvidenceWireSchema = ActivationEvidenceSchema;
export const ProductsListResponseWireSchema = ProductsListResponseSchema;
export const SubscriptionStartResponseWireSchema = SubscriptionStartResponseSchema;
export const SubscriptionStatusResponseWireSchema = SubscriptionStatusResponseSchema;
export const PurchaseStartResponseWireSchema = PurchaseStartResponseSchema;
export const PurchaseStatusResponseWireSchema = PurchaseStatusResponseSchema;
// END_BLOCK: RUNTIME_EXPORTS
