// ############################################################################
// AI_HEADER: MODULE_CONTRACTS_RUNTIME — handwritten barrel for runtime zod schemas.
// ROLE: Exports only stable, validated wire zod schemas generated from openapi.
// DEPENDENCIES: ./_generated.zod (autogenerated by scripts/contracts/generate.sh)
// ############################################################################

// START_MODULE_CONTRACT: M-WEB-CONTRACTS-RUNTIME
// purpose: Provide a handwritten barrel for generated runtime zod wire schemas.
// owns:
//   - packages/contracts/runtime.ts
// inputs:
//   - packages/contracts/_generated.zod.ts (autogenerated, do not edit)
// outputs:
//   - exports TodayPayloadWireSchema, TodayV2BlockWireSchema, ActivationEvidenceWireSchema
// dependencies:
//   - generated zod schemas
// side_effects: none
// emitted_logs: none
// invariants:
//   - exports only runtime zod validation schemas
//   - does not export any TypeScript-only types
// failure_policy: compile error on missing schema
// END_MODULE_CONTRACT: M-WEB-CONTRACTS-RUNTIME

// START_MODULE_MAP: M-WEB-CONTRACTS-RUNTIME
// public_entrypoints:
//   - TodayPayloadWireSchema
//   - TodayV2BlockWireSchema
//   - ActivationEvidenceWireSchema
// semantic_blocks:
//   - RUNTIME_EXPORTS
// owned_tests:
//   - __tests__/contracts/generated-runtime.test.ts
// END_MODULE_MAP: M-WEB-CONTRACTS-RUNTIME

// START_BLOCK: RUNTIME_EXPORTS
import {
  TodayPayload as TodayPayloadSchema,
  TodayV2Block as TodayV2BlockSchema,
  ActivationEvidence as ActivationEvidenceSchema,
} from "./_generated.zod";

export const TodayPayloadWireSchema = TodayPayloadSchema;
export const TodayV2BlockWireSchema = TodayV2BlockSchema;
export const ActivationEvidenceWireSchema = ActivationEvidenceSchema;
// END_BLOCK: RUNTIME_EXPORTS
