# ############################################################################
# AI_HEADER: MODULE_TODAY-SPHERE-PAGE — static sphere page orchestration.
# ROLE: Builds the authenticated sphere page from a sphere-scoped natal fact
#   pack and deterministic SolarSage activation periods.
# ############################################################################

# START_MODULE_CONTRACT: M-TODAY-SPHERE-PAGE
# purpose: Serve one canonical static sphere page with an honest natal content
#   state and a deterministic long-period layer.
# owns:
#   - apps/api/app/services/today_sphere_page_service.py
# inputs: authenticated user, profile, canonical sphere key, DB session, and
#   SolarSage/LLM provider responses.
# outputs: TodaySpherePagePayload.
# dependencies: AccessService, user-local-date resolver, Today convergence canon,
#   NatalContextService, SolarSageClient, LLMService, and the sphere narrative
#   persistence model.
# side_effects: reads/writes one natal narrative cache row; one sidecar period
#   request and at most one bounded LLM request on a natal cache miss.
# emitted_logs: sphere.natal_generation_completed,
#   sphere.natal_generation_failed.
# invariants:
#   - only full/preview access reaches the payload builder; locked access fails
#     before sidecar, natal, or LLM work;
#   - period evidence is filtered fail-closed through the frozen canon and is
#     never generated by the LLM;
#   - the LLM receives only the requested sphere fact pack;
#   - natal failures never produce template text or a null-content cache row;
#   - profile_hash and prompt_version are part of the natal cache identity.
# failure_policy: invalid input/access is raised as typed service errors;
#   sidecar and narrative failures return honest unavailable projections.
# END_MODULE_CONTRACT: M-TODAY-SPHERE-PAGE

# START_MODULE_CONTRACT: M-TODAY-SPHERE-NATAL-NARRATIVE
# purpose: Build, validate, and persist one claim-bound sphere natal narrative.
# owns:
#   - the sphere-scoped fact-pack and bounded provider boundary in this module.
# inputs: NatalContextData, canonical sphere mapping, birth-time mode, and
#   profile/prompt cache identity.
# outputs: TodaySphereNatal with ready paragraphs or unavailable/null content.
# dependencies: LLMService, TodaySphereNatalNarrative, and the public natal
#   wire schemas.
# side_effects: one provider call and one insert-on-conflict cache write on
#   successful generation; guarded generation logs.
# emitted_logs: sphere.natal_generation_completed,
#   sphere.natal_generation_failed.
# invariants:
#   - every paragraph has at least one sourceFactId from the fact pack;
#   - output contains at most four paragraphs and no forbidden time/relative-day
#     or unsupported special-point claims;
#   - bucket/unknown modes never expose houses, angles, or lots.
# failure_policy: provider, timeout, schema, claim, and capability failures are
#   converted to unavailable without persisting null content.
# END_MODULE_CONTRACT: M-TODAY-SPHERE-NATAL-NARRATIVE

# START_MODULE_MAP: M-TODAY-SPHERE-PAGE
# public_entrypoints:
#   - TodaySpherePageService.get_page
#   - build_sphere_natal_fact_pack
#   - build_sphere_natal_prompt
#   - InvalidSphereError
#   - ProfileIncompleteError
#   - AccessRequiredError
# semantic_blocks:
#   - ACCESS_AND_DATE: profile readiness, local date, and access gate.
#   - PERIOD_LAYER: deterministic activation-layer projection.
#   - NATAL_FACT_PACK: sphere-scoped deterministic natal facts.
#   - NATAL_GENERATION: bounded provider call and local validation.
#   - NATAL_CACHE: profile/prompt keyed insert-on-conflict persistence.
# owned_tests:
#   - apps/api/tests/test_today_sphere_page_service.py
#   - apps/api/tests/test_today_sphere_natal_postgres.py
# END_MODULE_MAP: M-TODAY-SPHERE-PAGE

from __future__ import annotations

import asyncio
import hashlib
import inspect
import json
import re
import time
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, date, datetime
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, get_args
from uuid import UUID

import yaml
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.clients.solarsage_client import get_solarsage_client
from app.core.config import settings
from app.core.logging import log_block, log_event
from app.db.models import TodaySphereNatalNarrative, User, UserProfile
from app.schemas.natal import NatalChartPlanet, NatalContextData
from app.schemas.today_convergence import BirthMode, CanonicalSphere
from app.schemas.today_sphere_page import (
    SpherePeriodTechnique,
    TodaySphereNatal,
    TodaySphereNatalContent,
    TodaySphereNatalParagraph,
    TodaySpherePagePayload,
    TodaySpherePeriodItem,
)
from app.services.access_service import AccessService
from app.services.astro_utils import strip_prefix
from app.services.natal_context_service import NatalContextService
from app.services.narrative_sanitizer import sanitize_narrative_text
from app.services.today_convergence_canon import TodayConvergenceCanon, load_today_convergence_canon
from app.services.user_local_date import UserLocalDateError, resolve_user_local_date


CANONICAL_SPHERES = frozenset(get_args(CanonicalSphere))
PERIOD_TECHNIQUES: tuple[SpherePeriodTechnique, ...] = (
    "annual_profection",
    "firdar_major",
    "firdar_minor",
    "solar_return",
)
SPHERE_NATAL_MAX_OUTPUT_TOKENS = 700
SPHERE_NATAL_TIMEOUT_SECONDS = 45.0

_CLOCK_TEXT_RE = re.compile(r"(?<!\d)\d{1,2}:\d{2}(?!\d)")
_RELATIVE_DAY_RE = re.compile(r"(?:сегодня|завтра|today|tomorrow)", re.IGNORECASE)
_CYRILLIC_RE = re.compile(r"[А-Яа-яЁё]")
_SPECIAL_POINT_RE = re.compile(
    r"(?:\bchiron\b|\bselena\b|\blilith\b|хирон|селена|лилит)",
    re.IGNORECASE,
)
_SPECIAL_POINT_FAMILIES: dict[str, frozenset[str]] = {
    "chiron": frozenset({"chiron", "хирон"}),
    "selena": frozenset({"selena", "селена"}),
    "lilith": frozenset({"lilith", "лилит"}),
}
_NATAL_TEMPLATE_RESIDUE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bprefixes\b", re.IGNORECASE),
    re.compile(r"знак\s+страсти", re.IGNORECASE),
    re.compile(r"часть\s+домов", re.IGNORECASE),
)

_PLANET_GENITIVE_RU: dict[str, str] = {
    "SUN": "Солнца",
    "MOON": "Луны",
    "MERCURY": "Меркурия",
    "VENUS": "Венеры",
    "MARS": "Марса",
    "JUPITER": "Юпитера",
    "SATURN": "Сатурна",
    "URANUS": "Урана",
    "NEPTUNE": "Нептуна",
    "PLUTO": "Плутона",
}
_PLANET_NOMINATIVE_RU: dict[str, str] = {
    "SUN": "Солнце",
    "MOON": "Луна",
    "MERCURY": "Меркурий",
    "VENUS": "Венера",
    "MARS": "Марс",
    "JUPITER": "Юпитер",
    "SATURN": "Сатурн",
    "URANUS": "Уран",
    "NEPTUNE": "Нептун",
    "PLUTO": "Плутон",
}

_SPHERE_NATAL_JSON_SCHEMA = {
    "name": "today_sphere_natal",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "paragraphs": {
                "type": "array",
                "minItems": 1,
                "maxItems": 4,
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string", "minLength": 1},
                        "sourceFactIds": {
                            "type": "array",
                            "minItems": 1,
                            "items": {"type": "string", "minLength": 1},
                        },
                    },
                    "required": ["text", "sourceFactIds"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["paragraphs"],
        "additionalProperties": False,
    },
}


class InvalidSphereError(ValueError):
    """The requested key is outside the frozen twelve-sphere set."""


class ProfileIncompleteError(ValueError):
    """The user is not onboarded or lacks required natal profile fields."""

    def __init__(self, missing_fields: Sequence[str] = ()) -> None:
        self.missing_fields = tuple(missing_fields)
        super().__init__("profile_incomplete")


class AccessRequiredError(ValueError):
    """The requested local day is outside the user's access window."""


class InvalidUserTimezoneError(ValueError):
    """The profile timezone cannot be resolved to a local date."""


class _NatalNarrativeError(ValueError):
    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


@dataclass(frozen=True)
class _PeriodCandidate:
    id: str
    technique: SpherePeriodTechnique
    title: str
    note: str
    target_kind: Literal["planet", "house"]
    target_value: str
    active_from: date
    active_until: date


@lru_cache(maxsize=1)
def _technical_sphere_definitions() -> dict[str, Mapping[str, Any]]:
    """Load the unchanged technical scoring canon used by period projection."""
    try:
        from app.services.canon_service import CANON_DIR

        path = Path(CANON_DIR) / "spheres.v1.yml"
        with path.open(encoding="utf-8") as stream:
            raw = yaml.safe_load(stream) or {}
    except (OSError, TypeError, ValueError, yaml.YAMLError):
        return {}

    spheres = raw.get("spheres") if isinstance(raw, Mapping) else None
    if not isinstance(spheres, Mapping):
        return {}
    return {
        str(technical_key).strip().lower(): definition
        for technical_key, definition in spheres.items()
        if isinstance(definition, Mapping)
    }


def _canonical_planet_name(value: object) -> str:
    return strip_prefix(str(value).strip()).upper() if value is not None else ""


def _canonical_sphere_or_raise(sphere_key: str, canon: TodayConvergenceCanon) -> str:
    normalized = sphere_key.strip().lower() if isinstance(sphere_key, str) else ""
    if normalized not in CANONICAL_SPHERES or normalized not in canon.canonical_spheres:
        raise InvalidSphereError(normalized)
    return normalized


def _house_numbers_for_sphere(
    sphere_key: str,
    canon: TodayConvergenceCanon,
) -> frozenset[int]:
    return frozenset(
        house
        for facet in canon.product_spheres[sphere_key].facets
        for house in facet.houses
    )


def _planet_technical_spheres(planet: str) -> frozenset[str]:
    """Return technical clusters that explicitly contain one planet."""
    normalized = _canonical_planet_name(planet)
    result: set[str] = set()
    for technical_key, definition in _technical_sphere_definitions().items():
        planets = definition.get("planets", ())
        if isinstance(planets, Mapping) and normalized in {
            _canonical_planet_name(name) for name in planets
        }:
            result.add(technical_key)
    return frozenset(result)


def _sphere_planets(sphere_key: str, canon: TodayConvergenceCanon) -> frozenset[str]:
    """Project the product sphere's allowed planet modifiers for natal facts."""
    return frozenset(
        _canonical_planet_name(planet)
        for facet in canon.product_spheres[sphere_key].facets
        for planet in facet.modifiers.get("planets", ())
    )


def _sphere_matches_planet(
    sphere_key: str,
    planet: str,
    canon: TodayConvergenceCanon,
) -> bool:
    """Map a period planet through technical clusters and product modifiers."""
    normalized = _canonical_planet_name(planet)
    technical_spheres = _planet_technical_spheres(normalized)
    product = canon.product_spheres[sphere_key]
    if any(
        technical_sphere in facet.technical_spheres
        for facet in product.facets
        for technical_sphere in technical_spheres
    ):
        return True
    return normalized in _sphere_planets(sphere_key, canon)


def _safe_date(value: object) -> date | None:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, str):
        text = value.strip()
        if "T" in text:
            text = text.split("T", 1)[0]
        try:
            return date.fromisoformat(text)
        except ValueError:
            return None
    return None


def _activation_entries(raw_layer: object) -> list[Mapping[str, Any]]:
    if hasattr(raw_layer, "model_dump"):
        raw_layer = raw_layer.model_dump(by_alias=True)
    if isinstance(raw_layer, Mapping):
        raw_entries: object = raw_layer.get("activations")
        if raw_entries is None:
            raw_entries = raw_layer.get("evidence", raw_layer.get("items"))
        if raw_entries is None and "technique" in raw_layer:
            raw_entries = [raw_layer]
    elif isinstance(raw_layer, Sequence) and not isinstance(raw_layer, (str, bytes)):
        raw_entries = raw_layer
    else:
        return []
    if not isinstance(raw_entries, Sequence) or isinstance(raw_entries, (str, bytes)):
        return []
    return [entry for entry in raw_entries if isinstance(entry, Mapping)]


def _activation_target(entry: Mapping[str, Any]) -> tuple[Literal["planet", "house"], str] | None:
    target_type = str(entry.get("target_type", entry.get("targetType", ""))).strip().lower()
    target_key = entry.get("target_key", entry.get("targetKey"))
    raw_house = entry.get("house")
    if target_type == "house" or (not target_type and raw_house is not None):
        raw_value = raw_house if raw_house is not None else target_key
        try:
            return "house", str(int(raw_value))
        except (TypeError, ValueError):
            return None

    # Some sidecar period evidence carries a diagnostic house alongside a
    # planet target (for example a solar-return angular planet).  The explicit
    # target_type is authoritative; an unknown target kind is fail-closed.
    if target_type not in {"", "planet"}:
        return None

    target_text = str(target_key or entry.get("target_planet", "")).strip()
    if target_text.upper() in {"HOUSE", "HOUSES"}:
        try:
            return "house", str(int(raw_house if raw_house is not None else target_key))
        except (TypeError, ValueError):
            return None
    planet = _canonical_planet_name(target_text)
    return ("planet", planet) if planet else None


def _period_matches_sphere(
    entry: Mapping[str, Any],
    sphere_key: str,
    canon: TodayConvergenceCanon,
) -> tuple[Literal["planet", "house"], str] | None:
    target = _activation_target(entry)
    if target is None:
        return None
    target_kind, target_value = target
    if target_kind == "house":
        return target if int(target_value) in _house_numbers_for_sphere(sphere_key, canon) else None

    # Solar-return payloads may carry a diagnostic house alongside a planet.
    # That house is more specific than the planet's broad technical mapping.
    raw_house = entry.get("house")
    try:
        diagnostic_house = int(raw_house) if raw_house is not None else None
    except (TypeError, ValueError):
        diagnostic_house = None
    if diagnostic_house in _house_numbers_for_sphere(sphere_key, canon):
        return target
    return target if _sphere_matches_planet(sphere_key, target_value, canon) else None


def _period_title(
    technique: SpherePeriodTechnique,
    target_kind: Literal["planet", "house"],
    target_value: str,
) -> str:
    if target_kind == "house":
        if technique == "annual_profection":
            return f"Год профекции: {target_value} дом"
        if technique == "solar_return":
            return f"Соляр: {target_value} дом"
        return f"{('Большой' if technique == 'firdar_major' else 'Малый')} фирдар: {target_value} дом"

    if technique == "firdar_major":
        return f"Большой фирдар {_PLANET_GENITIVE_RU.get(target_value, target_value)}"
    if technique == "firdar_minor":
        return f"Малый фирдар {_PLANET_GENITIVE_RU.get(target_value, target_value)}"
    if technique == "annual_profection":
        return f"Год профекции: {_PLANET_GENITIVE_RU.get(target_value, target_value)}"
    return f"Соляр: {_PLANET_NOMINATIVE_RU.get(target_value, target_value)}"


_PLANET_PERIOD_MEANINGS: dict[str, str] = {
    "SUN": "самовыражение и ясные цели",
    "MOON": "эмоции, привычки и ощущение опоры",
    "MERCURY": "мысли, расчёты и разговоры",
    "VENUS": "ценности, симпатии и удовольствие",
    "MARS": "действия, темп и физическая энергия",
    "JUPITER": "рост, знания и расширение возможностей",
    "SATURN": "дисциплина, границы и долгие обязательства",
    "URANUS": "обновления, свобода и неожиданные повороты",
    "NEPTUNE": "воображение, чувствительность и внутренний образ",
    "PLUTO": "глубокая перестройка и контроль ресурсов",
}
_SPHERE_PERIOD_TOPICS: dict[str, str] = {
    "work": "рабочих задач и карьеры",
    "finance": "денег и ресурсов",
    "documents": "документов и оформления",
    "relationships": "отношений и партнёрства",
    "sport": "движения и тренировок",
    "communication": "общения и договорённостей",
    "health": "самочувствия и режима",
    "home_family": "дома и семейной опоры",
    "travel": "поездок и расширения горизонта",
    "creativity": "творчества и самовыражения",
    "study": "учёбы и развития навыков",
    "friends_goals": "друзей, сообществ и планов",
}
_SPHERE_PERIOD_EFFECTS: dict[str, str] = {
    "work": "результат растёт через последовательные действия",
    "finance": "личные ресурсы и обязательства требуют общей системы",
    "documents": "ясные формулировки и порядок в бумагах экономят силы",
    "relationships": "важны равный обмен и заранее оговорённые правила",
    "sport": "нагрузка лучше работает в устойчивом, повторяемом режиме",
    "communication": "разговоры и договорённости стоит сразу переводить в ясные шаги",
    "health": "режим и восстановление важнее разовых рывков",
    "home_family": "решения о быте и опоре закрепляются надолго",
    "travel": "расширение маршрута требует подготовки и гибкости",
    "creativity": "идеи получают форму, когда для них выделено регулярное место",
    "study": "система и практика дают больше, чем разрозненные усилия",
    "friends_goals": "новые связи помогают пересмотреть направление и цели",
}


def _period_note(
    sphere_key: str,
    technique: SpherePeriodTechnique,
    target_kind: Literal["planet", "house"],
    target_value: str,
) -> str:
    """Build a short human explanation without starting another provider call."""
    topic = _SPHERE_PERIOD_TOPICS.get(sphere_key, sphere_key)
    effect = _SPHERE_PERIOD_EFFECTS.get(sphere_key, "тема раскрывается через последовательные решения")
    technique_text = {
        "firdar_major": "Большой фирдар задаёт длинный фон",
        "firdar_minor": "Малый фирдар показывает акцент ближайшего периода",
        "annual_profection": "Год профекции делает эту тему заметной в течение года",
        "solar_return": "Соляр описывает сюжет личного года",
    }[technique]
    if target_kind == "house":
        return f"{technique_text}: {target_value}-й дом связан с темой {topic}. Здесь полезно помнить, что {effect}."
    planet = _PLANET_NOMINATIVE_RU.get(target_value, target_value)
    meaning = _PLANET_PERIOD_MEANINGS.get(target_value, "свойства выбранного фактора")
    return f"{planet} — это {meaning}. {technique_text} применительно к теме {topic}: {effect}."


def _period_synthesis(
    sphere_key: str,
    items: Sequence[TodaySpherePeriodItem],
    canon: TodayConvergenceCanon,
) -> str | None:
    """Summarize the active period stack; empty layers remain explicitly null."""
    if not items:
        return None
    title = canon.product_spheres[sphere_key].title.casefold()
    if len(items) == 1:
        return f"Период «{items[0].title}» задаёт основной фон темы «{title}»."
    titles = ", ".join(item.title for item in items)
    effect = _SPHERE_PERIOD_EFFECTS.get(sphere_key, "тема усиливается через последовательные решения")
    return f"Одновременно действуют {len(items)} периода в теме «{title}»: {titles}. Их сумма: {effect}."


def _period_item_id(technique: str, target: str, active_from: date) -> str:
    value = f"{technique}|{target}|{active_from.isoformat()}"
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:32]


def _period_identity(items: Sequence[TodaySpherePeriodItem]) -> str:
    value = "|".join(
        f"{item.id}:{item.active_from.isoformat()}:{item.active_until.isoformat()}"
        for item in items
    )
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:32]


def _special_point_names(context: NatalContextData) -> tuple[str, ...]:
    return tuple(
        sorted(
            {
                _canonical_planet_name(point.name)
                for point in context.special_points
                if point.name and _canonical_planet_name(point.name)
            }
        )
    )


def _special_point_family(value: str) -> str:
    normalized = value.casefold()
    for family, aliases in _SPECIAL_POINT_FAMILIES.items():
        if any(alias in normalized for alias in aliases):
            return family
    return normalized


def _planet_fact(planet: NatalChartPlanet, *, include_house: bool) -> dict[str, Any]:
    name = _canonical_planet_name(planet.name)
    fact: dict[str, Any] = {
        "id": f"natal:planet:{name}",
        "kind": "planet",
        "name": name,
        "sign": planet.sign,
        "degree": planet.degree,
        "longitude": planet.longitude,
        "retrograde": planet.retrograde,
    }
    if include_house and planet.house is not None:
        fact["house"] = planet.house
    return fact


def build_sphere_natal_fact_pack(
    context: NatalContextData,
    sphere_key: str,
    birth_time_mode: BirthMode,
    canon: TodayConvergenceCanon | None = None,
) -> dict[str, Any]:
    # START_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-NATAL-NARRATIVE.build_fact_pack
    # purpose: Project only the requested sphere's deterministic natal facts.
    # inputs: validated NatalContextData, canonical sphere key, birth-time mode,
    #   and optional loaded convergence canon.
    # returns: JSON-safe sphere-scoped pack with deterministic fact ids.
    # side_effects: none.
    # emitted_logs: none.
    # error_behavior: raises InvalidSphereError for a non-canonical sphere.
    # END_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-NATAL-NARRATIVE.build_fact_pack
    active_canon = canon or load_today_convergence_canon()
    sphere = _canonical_sphere_or_raise(sphere_key, active_canon)
    exact = birth_time_mode == "exact"
    selected_planets = _sphere_planets(sphere, active_canon)
    related_houses = _house_numbers_for_sphere(sphere, active_canon) if exact else frozenset()

    planets = [
        _planet_fact(planet, include_house=exact)
        for planet in context.planets
        if _canonical_planet_name(planet.name) in selected_planets
    ]
    planets.sort(key=lambda fact: fact["id"])
    selected_ids = {fact["name"] for fact in planets}

    houses: list[dict[str, Any]] = []
    if exact:
        houses = [
            {
                "id": f"natal:house:{house.number}",
                "kind": "house",
                "number": house.number,
                "sign": house.sign,
                "degree": house.degree,
                "longitude": house.longitude,
            }
            for house in context.houses
            if house.number in related_houses
        ]
        houses.sort(key=lambda fact: (fact["number"], fact["id"]))

    aspects: list[dict[str, Any]] = []
    seen_aspects: set[str] = set()
    for aspect in context.aspects:
        planet_a = _canonical_planet_name(aspect.planet_a)
        planet_b = _canonical_planet_name(aspect.planet_b)
        if not ({planet_a, planet_b} & selected_ids):
            continue
        ordered = tuple(sorted((planet_a, planet_b)))
        if not all(ordered) or ordered[0] == ordered[1]:
            continue
        fact_id = f"natal:aspect:{ordered[0]}-{ordered[1]}"
        if fact_id in seen_aspects:
            continue
        seen_aspects.add(fact_id)
        aspects.append(
            {
                "id": fact_id,
                "kind": "aspect",
                "planetA": ordered[0],
                "planetB": ordered[1],
                "aspectType": aspect.aspect_type,
                "orb": aspect.orb,
                "applying": aspect.applying,
            }
        )
    aspects.sort(key=lambda fact: fact["id"])

    facts: list[dict[str, Any]] = [*planets, *houses, *aspects]
    score = context.sphere_scores.get(sphere)
    if score is not None:
        facts.append(
            {
                "id": f"natal:score:{sphere}",
                "kind": "score",
                "sphere": sphere,
                "value": score,
            }
        )

    dominant_names = [
        _canonical_planet_name(name)
        for name in context.dominants
        if _canonical_planet_name(name) in selected_ids
    ]
    dominant_names = sorted(set(dominant_names))

    return {
        "sphere": sphere,
        "birthTimeMode": birth_time_mode,
        "housesAvailable": exact,
        "facts": facts,
        "dominants": dominant_names,
        "availableSpecialPoints": list(_special_point_names(context)) if exact else [],
    }


def build_sphere_natal_prompt(
    fact_pack: Mapping[str, Any],
    sphere_key: str,
    prompt_version: str,
) -> str:
    # START_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-NATAL-NARRATIVE.build_prompt
    # purpose: Build the bounded Russian prompt from one sphere-scoped fact pack.
    # inputs: fact_pack, canonical sphere key, and prompt version.
    # returns: strict-JSON generation prompt.
    # side_effects: none.
    # emitted_logs: none.
    # error_behavior: raises ValueError for invalid prompt identity or pack.
    # END_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-NATAL-NARRATIVE.build_prompt
    if not isinstance(prompt_version, str) or not prompt_version.strip() or len(prompt_version) > 64:
        raise ValueError("sphere_natal:prompt_version")
    encoded_pack = json.dumps(fact_pack, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return f"""Ты пишешь короткий натальный текст для сферы «{sphere_key}».
Версия промпта: {prompt_version}.

Используй только факты из JSON-пакета ниже. Пиши по-русски, на «ты», без
фатализма и без прогноза по календарной дате. Не добавляй новые планеты,
дома, аспекты или специальные точки. Не используй слова «сегодня» и
«завтра», точное время формата HH:MM или неподтверждённые Хирон, Селену,
Лилит. Не используй Transit_, Natal_, слово Planet или перечисления вида
«M, Mars»/«M, <Planet>»; называй планеты только обычными русскими словами.
Если факт нельзя так назвать, верни другой абзац или не включай его.
Если упоминаешь факт, привяжи абзац к одному или нескольким его id.

Верни только JSON строго такой формы, не добавляй markdown:
{{"paragraphs":[{{"text":"...","sourceFactIds":["natal:planet:SUN"]}}]}}
Нужно от 1 до 4 непустых абзацев; каждый sourceFactIds должен быть непустым.

SPHERE FACT PACK:
{encoded_pack}
"""


def _provider_method(client: object) -> tuple[Callable[..., object], str]:
    for name in ("generate_json", "generate", "complete", "_generate_text"):
        method = getattr(client, name, None)
        if callable(method):
            return method, name
    if callable(client):
        return client, "__call__"
    raise TypeError("llm client has no supported call method")


def _provider_kwargs(
    method: Callable[..., object],
    method_name: str,
    deadline_at: float,
) -> dict[str, Any]:
    try:
        parameters = inspect.signature(method).parameters
    except (TypeError, ValueError):
        parameters = {}
    accepts_kwargs = any(
        parameter.kind is inspect.Parameter.VAR_KEYWORD
        for parameter in parameters.values()
    )

    def supports(name: str) -> bool:
        return accepts_kwargs or name in parameters

    kwargs: dict[str, Any] = {}
    if supports("max_output_tokens"):
        kwargs["max_output_tokens"] = SPHERE_NATAL_MAX_OUTPUT_TOKENS
    elif supports("max_tokens"):
        kwargs["max_tokens"] = SPHERE_NATAL_MAX_OUTPUT_TOKENS
    if supports("timeout_seconds"):
        kwargs["timeout_seconds"] = SPHERE_NATAL_TIMEOUT_SECONDS
    elif supports("timeout"):
        kwargs["timeout"] = SPHERE_NATAL_TIMEOUT_SECONDS
    if supports("deadline_at"):
        kwargs["deadline_at"] = deadline_at
    if supports("json_object"):
        kwargs["json_object"] = True
    if supports("json_schema"):
        kwargs["json_schema"] = _SPHERE_NATAL_JSON_SCHEMA
    return kwargs


def _decode_provider_value(value: object) -> object:
    if isinstance(value, (str, bytes)):
        if isinstance(value, bytes):
            return value.decode("utf-8")
        return value
    if isinstance(value, Mapping):
        if "paragraphs" in value:
            return value
        for key in ("text", "content", "output", "response"):
            if key in value:
                return _decode_provider_value(value[key])
        return value
    raw = getattr(value, "text", getattr(value, "content", None))
    return _decode_provider_value(raw) if raw is not None else value


async def _call_natal_provider(client: object, prompt: str) -> object:
    method, method_name = _provider_method(client)
    deadline_at = time.monotonic() + SPHERE_NATAL_TIMEOUT_SECONDS
    result = method(prompt, **_provider_kwargs(method, method_name, deadline_at))
    return await asyncio.wait_for(result, timeout=SPHERE_NATAL_TIMEOUT_SECONDS) if inspect.isawaitable(result) else result


def _validate_natal_provider_response(
    raw_response: object,
    allowed_fact_ids: frozenset[str],
    available_special_points: frozenset[str],
) -> TodaySphereNatalContent:
    raw_response = _decode_provider_value(raw_response)
    if isinstance(raw_response, str):
        text = raw_response.strip()
        if "```" in text:
            text = text.replace("```json", "").replace("```", "").strip()
        try:
            parsed: object = json.loads(text)
        except (TypeError, ValueError, json.JSONDecodeError) as exc:
            raise _NatalNarrativeError("schema_invalid") from exc
    else:
        parsed = raw_response

    if not isinstance(parsed, Mapping) or set(parsed) != {"paragraphs"}:
        raise _NatalNarrativeError("schema_invalid")
    raw_paragraphs = parsed["paragraphs"]
    if not isinstance(raw_paragraphs, list) or not 1 <= len(raw_paragraphs) <= 4:
        raise _NatalNarrativeError("schema_invalid")

    paragraphs: list[TodaySphereNatalParagraph] = []
    for raw_paragraph in raw_paragraphs:
        if not isinstance(raw_paragraph, Mapping) or set(raw_paragraph) != {"text", "sourceFactIds"}:
            raise _NatalNarrativeError("schema_invalid")
        text_value = raw_paragraph["text"]
        source_ids = raw_paragraph["sourceFactIds"]
        if not isinstance(text_value, str) or not text_value.strip():
            raise _NatalNarrativeError("schema_invalid")
        if not isinstance(source_ids, list) or not source_ids:
            raise _NatalNarrativeError("claim_binding")
        if any(not isinstance(source_id, str) or not source_id.strip() for source_id in source_ids):
            raise _NatalNarrativeError("claim_binding")
        if len(source_ids) != len(set(source_ids)) or not set(source_ids).issubset(allowed_fact_ids):
            raise _NatalNarrativeError("claim_binding")
        clean_text = sanitize_narrative_text(text_value)
        if clean_text is None:
            raise _NatalNarrativeError("schema_invalid")
        # Known fragments of the retired natal templates must never enter the
        # cache or wire response.  Keep this fail-closed at the provider
        # boundary so the existing unavailable state remains honest.
        if any(pattern.search(clean_text) for pattern in _NATAL_TEMPLATE_RESIDUE_PATTERNS):
            raise _NatalNarrativeError("schema_invalid")
        clean_text = re.sub(r"ответственой", "ответственной", clean_text, flags=re.IGNORECASE)
        if _CLOCK_TEXT_RE.search(clean_text) or _RELATIVE_DAY_RE.search(clean_text):
            raise _NatalNarrativeError("capability_violation")
        if _SPECIAL_POINT_RE.search(clean_text):
            mentioned = {
                _special_point_family(match.group(0))
                for match in _SPECIAL_POINT_RE.finditer(clean_text)
            }
            allowed = {
                _special_point_family(name) for name in available_special_points
            }
            if any(name not in allowed for name in mentioned):
                raise _NatalNarrativeError("claim_binding")
        if not _CYRILLIC_RE.search(clean_text):
            raise _NatalNarrativeError("capability_violation")
        paragraphs.append(
            TodaySphereNatalParagraph(text=clean_text, source_fact_ids=list(source_ids))
        )
    return TodaySphereNatalContent(paragraphs=paragraphs)


def _natal_error_code(exc: BaseException) -> str:
    if isinstance(exc, (asyncio.TimeoutError, TimeoutError)) or "timeout" in type(exc).__name__.casefold():
        return "timeout"
    if isinstance(exc, _NatalNarrativeError):
        return exc.code
    return "provider_error"


def _guarded_natal_log(
    event: str,
    *,
    level: str,
    sphere_key: str,
    prompt_version: str | None = None,
    latency_ms: int,
    paragraphs: int | None = None,
    error_code: str | None = None,
) -> None:
    try:
        with log_block(
            slice="W-TODAY-CONVERGENCE-P4",
            module="M-TODAY-SPHERE-NATAL-NARRATIVE",
            block="NATAL_GENERATION",
        ):
            payload: dict[str, Any] = {
                "sphere": sphere_key,
                "latency_ms": latency_ms,
            }
            if prompt_version is not None:
                payload["prompt_version"] = prompt_version
            if paragraphs is not None:
                payload["paragraphs"] = paragraphs
            if error_code is not None:
                payload["error_code"] = error_code
            log_event(event, level=level, payload=payload)
    except Exception:
        # Observability must never change the content outcome.
        pass


class TodaySpherePageService:
    def __init__(
        self,
        db: AsyncSession,
        *,
        llm: object | None = None,
        clock: Callable[[], datetime] | None = None,
        canon: TodayConvergenceCanon | None = None,
    ) -> None:
        self.db = db
        self.llm = llm
        self.clock = clock or (lambda: datetime.now(UTC))
        self.canon = canon or load_today_convergence_canon()

    # START_BLOCK: ACCESS_AND_DATE
    async def _load_user(self, user_id: UUID) -> User:
        result = await self.db.execute(
            select(User).where(User.id == user_id).options(selectinload(User.profile))
        )
        user = result.scalar_one_or_none()
        if user is None:
            raise ProfileIncompleteError()
        return user

    @staticmethod
    def _validate_profile(profile: UserProfile | None) -> UserProfile:
        if profile is None or not profile.is_onboarded:
            raw_missing = NatalContextService.missing_profile_fields(profile)
            raise ProfileIncompleteError(
                [f for f in raw_missing if not (f == "birth_time" and profile and profile.birth_time_mode in ("unknown", "bucket"))]
            )
        missing = [
            field for field in NatalContextService.missing_profile_fields(profile)
            if not (field == "birth_time" and profile.birth_time_mode in ("unknown", "bucket"))
        ]
        if missing:
            raise ProfileIncompleteError(missing)
        return profile

    async def get_page(
        self,
        user_id: UUID,
        sphere_key: str,
    ) -> TodaySpherePagePayload:
        # START_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-PAGE.get_page
        # purpose: Authorize and build one static sphere page for the current
        #   local date without exposing Today snapshot evidence.
        # inputs: authenticated user UUID and canonical sphere key.
        # returns: TodaySpherePagePayload with natal and period layers.
        # side_effects: DB reads/cache write, one activation-layer request, and
        #   at most one bounded natal LLM request.
        # emitted_logs: sphere.natal_generation_completed,
        #   sphere.natal_generation_failed.
        # error_behavior: typed invalid/profile/access/timezone errors are left
        #   for the route to map; downstream generation failures are honest.
        # END_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-PAGE.get_page
        normalized_sphere = sphere_key.strip().lower() if isinstance(sphere_key, str) else ""
        if normalized_sphere not in CANONICAL_SPHERES:
            raise InvalidSphereError(normalized_sphere)

        user = await self._load_user(user_id)
        profile = self._validate_profile(user.profile)
        try:
            target_date = resolve_user_local_date(user, self.clock())
        except UserLocalDateError as exc:
            raise InvalidUserTimezoneError(exc.code) from None

        access = await AccessService(self.db).can_access_day(user.id, target_date)
        if access.state == "locked":
            raise AccessRequiredError("access_required")

        birth_time_mode = profile.birth_time_mode
        if birth_time_mode not in ("exact", "bucket", "unknown"):
            birth_time_mode = "unknown"
        profile_hash = NatalContextService.compute_profile_hash(profile)
        period, period_unavailable = await self._build_period_layer(profile, target_date, normalized_sphere)
        natal = await self._build_natal_layer(
            user.id,
            profile,
            normalized_sphere,
            birth_time_mode,
            profile_hash,
        )
        return TodaySpherePagePayload(
            sphere=normalized_sphere,
            birth_time_mode=birth_time_mode,
            houses_available=birth_time_mode == "exact",
            natal=natal,
            period=period,
            period_identity="" if period_unavailable else _period_identity(
                period
            ),
            period_unavailable=period_unavailable,
            period_synthesis=None if period_unavailable else _period_synthesis(
                normalized_sphere,
                period,
                self.canon,
            ),
        )
    # END_BLOCK: ACCESS_AND_DATE

    # START_BLOCK: PERIOD_LAYER
    async def _build_period_layer(
        self,
        profile: UserProfile,
        target_date: date,
        sphere_key: str,
    ) -> tuple[list[TodaySpherePeriodItem], bool]:
        # START_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-PAGE.build_period_layer
        # purpose: Fetch and deterministically project the four approved
        #   activation techniques for one sphere.
        # inputs: complete profile, user-local target date, and sphere key.
        # returns: at most five sorted period items plus sidecar-unavailable flag.
        # side_effects: exactly one SolarSage activation-layer request.
        # emitted_logs: none.
        # error_behavior: sidecar failures return empty layer with unavailable=true.
        # END_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-PAGE.build_period_layer
        try:
            client = get_solarsage_client()
            raw_layer = await client.get_activation_layer(
                birth_date=profile.birthday.isoformat(),  # type: ignore[union-attr]
                birth_time=profile.birth_time.strftime("%H:%M") if profile.birth_time else "12:00",
                birth_lat=float(profile.birth_lat),  # type: ignore[arg-type]
                birth_lon=float(profile.birth_lon),  # type: ignore[arg-type]
                birth_tz=profile.birth_tz,  # type: ignore[arg-type]
                target_date=target_date.isoformat(),
                target_time="12:00",
                target_tz=profile.current_tz or profile.birth_tz or "UTC",
                house_system="PLACIDUS",
                techniques=list(PERIOD_TECHNIQUES),
            )
        except asyncio.CancelledError:
            raise
        except Exception:
            return [], True

        entries = _activation_entries(raw_layer)
        candidates: dict[str, _PeriodCandidate] = {}
        for entry in entries:
            technique = str(entry.get("technique", "")).strip().lower()
            if technique not in PERIOD_TECHNIQUES:
                continue
            target = _period_matches_sphere(entry, sphere_key, self.canon)
            if target is None:
                continue
            active_from = _safe_date(entry.get("active_from", entry.get("activeFrom")))
            active_until = _safe_date(entry.get("active_until", entry.get("activeUntil")))
            if active_from is None or active_until is None or active_until < active_from:
                continue
            target_kind, target_value = target
            item_id = _period_item_id(technique, f"{target_kind}:{target_value}", active_from)
            candidate = _PeriodCandidate(
                id=item_id,
                technique=technique,  # type: ignore[arg-type]
                title=_period_title(technique, target_kind, target_value),  # type: ignore[arg-type]
                note=_period_note(
                    sphere_key,
                    technique,  # type: ignore[arg-type]
                    target_kind,
                    target_value,
                ),
                target_kind=target_kind,
                target_value=target_value,
                active_from=active_from,
                active_until=active_until,
            )
            candidates[item_id] = candidate

        ordered = sorted(candidates.values(), key=lambda item: (item.active_until, item.id))[:5]
        return [
            TodaySpherePeriodItem(
                id=item.id,
                technique=item.technique,
                title=item.title,
                note=item.note,
                active_from=item.active_from,
                active_until=item.active_until,
            )
            for item in ordered
        ], False
    # END_BLOCK: PERIOD_LAYER

    # START_BLOCK: NATAL_CACHE
    async def _load_cached_natal(
        self,
        user_id: UUID,
        profile_hash: str,
        sphere_key: str,
        prompt_version: str,
    ) -> TodaySphereNatalContent | None:
        result = await self.db.execute(
            select(TodaySphereNatalNarrative).where(
                TodaySphereNatalNarrative.user_id == user_id,
                TodaySphereNatalNarrative.profile_hash == profile_hash,
                TodaySphereNatalNarrative.sphere_key == sphere_key,
                TodaySphereNatalNarrative.prompt_version == prompt_version,
            )
        )
        row = result.scalar_one_or_none()
        if row is None or row.content_json is None:
            return None
        try:
            content = TodaySphereNatalContent.model_validate(row.content_json)
            cleaned_paragraphs: list[TodaySphereNatalParagraph] = []
            for paragraph in content.paragraphs:
                clean_text = sanitize_narrative_text(paragraph.text)
                if clean_text is None or any(
                    pattern.search(clean_text)
                    for pattern in _NATAL_TEMPLATE_RESIDUE_PATTERNS
                ):
                    return None
                clean_text = re.sub(
                    r"ответственой", "ответственной", clean_text, flags=re.IGNORECASE
                )
                cleaned_paragraphs.append(paragraph.model_copy(update={"text": clean_text}))
            return content.model_copy(update={"paragraphs": cleaned_paragraphs})
        except Exception:
            return None

    async def _persist_natal(
        self,
        user_id: UUID,
        profile_hash: str,
        sphere_key: str,
        prompt_version: str,
        content: TodaySphereNatalContent,
    ) -> TodaySphereNatalContent:
        row = TodaySphereNatalNarrative(
            user_id=user_id,
            profile_hash=profile_hash,
            sphere_key=sphere_key,
            prompt_version=prompt_version,
            content_json=content.model_dump(by_alias=True),
        )
        self.db.add(row)
        try:
            await self.db.commit()
        except IntegrityError:
            await self.db.rollback()
        cached = await self._load_cached_natal(user_id, profile_hash, sphere_key, prompt_version)
        if cached is None:
            raise RuntimeError("sphere_natal_cache_write_failed")
        return cached
    # END_BLOCK: NATAL_CACHE

    # START_BLOCK: NATAL_GENERATION
    async def _build_natal_layer(
        self,
        user_id: UUID,
        profile: UserProfile,
        sphere_key: str,
        birth_time_mode: BirthMode,
        profile_hash: str,
    ) -> TodaySphereNatal:
        # START_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-NATAL-NARRATIVE.build_natal_layer
        # purpose: Load or generate one profile/prompt/sphere keyed natal narrative.
        # inputs: user/profile identity, sphere, birth-time mode, and profile hash.
        # returns: ready claim-bound narrative or unavailable/null content.
        # side_effects: natal context read/build, one provider call, and an
        # insert-on-conflict cache write only after successful validation.
        # emitted_logs: sphere.natal_generation_completed,
        #   sphere.natal_generation_failed.
        # error_behavior: all expected generation/cache failures return unavailable.
        # END_FUNCTION_CONTRACT: F-M-TODAY-SPHERE-NATAL-NARRATIVE.build_natal_layer
        prompt_version = settings.today_sphere_natal_prompt_version
        cached = await self._load_cached_natal(
            user_id, profile_hash, sphere_key, prompt_version
        )
        if cached is not None:
            return TodaySphereNatal(state="ready", paragraphs=cached.paragraphs)

        started_at = time.monotonic()
        try:
            context = await NatalContextService(self.db).get_or_build_natal_context(user_id)
            if not isinstance(context, NatalContextData):
                context = NatalContextData.model_validate(context)
            fact_pack = build_sphere_natal_fact_pack(
                context,
                sphere_key,
                birth_time_mode,
                self.canon,
            )
            allowed_fact_ids = frozenset(
                fact["id"] for fact in fact_pack["facts"] if isinstance(fact, Mapping) and isinstance(fact.get("id"), str)
            )
            prompt = build_sphere_natal_prompt(fact_pack, sphere_key, prompt_version)
            provider = self.llm
            if provider is None:
                from app.services.llm_service import LLMService

                provider = LLMService()
            raw_response = await _call_natal_provider(provider, prompt)
            content = _validate_natal_provider_response(
                raw_response,
                allowed_fact_ids,
                frozenset(fact_pack["availableSpecialPoints"]),
            )
            persisted = await self._persist_natal(
                user_id,
                profile_hash,
                sphere_key,
                prompt_version,
                content,
            )
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            error_code = _natal_error_code(exc)
            _guarded_natal_log(
                "sphere.natal_generation_failed",
                level="warn",
                sphere_key=sphere_key,
                prompt_version=None,
                latency_ms=int((time.monotonic() - started_at) * 1000),
                error_code=error_code,
            )
            return TodaySphereNatal(state="unavailable", paragraphs=None)

        latency_ms = int((time.monotonic() - started_at) * 1000)
        _guarded_natal_log(
            "sphere.natal_generation_completed",
            level="info",
            sphere_key=sphere_key,
            prompt_version=prompt_version,
            latency_ms=latency_ms,
            paragraphs=len(persisted.paragraphs),
        )
        return TodaySphereNatal(state="ready", paragraphs=persisted.paragraphs)
    # END_BLOCK: NATAL_GENERATION


__all__ = [
    "CANONICAL_SPHERES",
    "PERIOD_TECHNIQUES",
    "InvalidSphereError",
    "ProfileIncompleteError",
    "AccessRequiredError",
    "InvalidUserTimezoneError",
    "TodaySpherePageService",
    "build_sphere_natal_fact_pack",
    "build_sphere_natal_prompt",
]
